
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TWS
 */
public class EditRD extends javax.swing.JFrame {

        public void editClear2(){
              editJRDSI.setText(null);
              editJRDLNS.setText(null);
              editJRDMP.setText(null);
              editJRDNCD.setText(null);
              editJRDNC1.setText(null);
              editJDRDDOB1.setDate(null);
              editJRDSC1.setSelectedItem(null);
              editJRDNC2.setText(null);
              editJRDDOB2.setDate(null);
              editJRDSC2.setSelectedItem(null);
              editJRDNC3.setText(null);
              editJRDDOB3.setDate(null);
              editJRDSC3.setSelectedItem(null);
              editJRDNC4.setText(null);
              editJRDDOB4.setDate(null);
              editJRDSC4.setSelectedItem(null);
              editJRDNK.setText(null);
              editJRDANK.setText(null);
              editJRDNDOB.setDate(null);
              editJRDNG.setSelectedItem(null);
              editJRDNR.setText(null);
              editJRDNMN.setText(null);
              editJRDNON.setText(null);
              editJRDNRAS.setText(null);
              editJRDNNBS.setText(null);
              editJRDNCT.setText(null);
              editJRDLGA_L.setText(null);
              editJRDST.setSelectedItem(null);
              editJRDIC.setText(null);
              editJRDIMN.setText(null);

            
        }
    /**
     * Creates new form EditRD
     */
    public EditRD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        RDNCD_L = new javax.swing.JLabel();
        editJRDNMN = new javax.swing.JTextField();
        RDNK_L = new javax.swing.JLabel();
        RDNRAS_L1 = new javax.swing.JLabel();
        RDNNBS_L = new javax.swing.JLabel();
        RDNC1_L = new javax.swing.JLabel();
        RDDOB3_L = new javax.swing.JLabel();
        editJRDSC1 = new javax.swing.JComboBox();
        RDNON_L = new javax.swing.JLabel();
        editJRDDOB2 = new com.toedter.calendar.JDateChooser();
        editJRDNC1 = new javax.swing.JTextField();
        editJRDST = new javax.swing.JComboBox();
        RDIC_L = new javax.swing.JLabel();
        editJRDSC4 = new javax.swing.JComboBox();
        editJRDIC = new javax.swing.JTextField();
        editJRDNC2 = new javax.swing.JTextField();
        editJRDDOB3 = new com.toedter.calendar.JDateChooser();
        editJRDSI = new javax.swing.JTextField();
        RDST_L = new javax.swing.JLabel();
        RDNC3_L = new javax.swing.JLabel();
        editJRDIMN = new javax.swing.JTextField();
        RDLGA_L = new javax.swing.JLabel();
        RDNMN_L = new javax.swing.JLabel();
        RDDOB1_L = new javax.swing.JLabel();
        editJRDNON = new javax.swing.JTextField();
        RDNC4_L = new javax.swing.JLabel();
        RDNDOB_L = new javax.swing.JLabel();
        RDNRAS_L = new javax.swing.JLabel();
        RDLNS_L = new javax.swing.JLabel();
        RDNG_L = new javax.swing.JLabel();
        RDSC1_L = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editJRDANK = new javax.swing.JTextArea();
        editJRDNRAS = new javax.swing.JTextField();
        editJRDNK = new javax.swing.JTextField();
        RDDOB2_L = new javax.swing.JLabel();
        editJRDMP = new javax.swing.JTextField();
        editJRDSC2 = new javax.swing.JComboBox();
        editJRDNC3 = new javax.swing.JTextField();
        editJRDNCD = new javax.swing.JTextField();
        editJDRDDOB1 = new com.toedter.calendar.JDateChooser();
        RDNC2_L = new javax.swing.JLabel();
        editJRDNCT = new javax.swing.JTextField();
        editJRDLGA_L = new javax.swing.JTextField();
        editJRDNG = new javax.swing.JComboBox();
        RDSC3_L = new javax.swing.JLabel();
        editJRDNNBS = new javax.swing.JTextField();
        editJRDNDOB = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RDNCT_L = new javax.swing.JLabel();
        editJRDLNS = new javax.swing.JTextField();
        editJRDDOB4 = new com.toedter.calendar.JDateChooser();
        RDNC4_L3 = new javax.swing.JLabel();
        editJRDSC3 = new javax.swing.JComboBox();
        RDSC4_L = new javax.swing.JLabel();
        RDMP_L = new javax.swing.JLabel();
        RDSC2_L = new javax.swing.JLabel();
        RDNR_L = new javax.swing.JLabel();
        RDDOB4_L = new javax.swing.JLabel();
        RDIMN_L = new javax.swing.JLabel();
        RDSI = new javax.swing.JLabel();
        editJRDNR = new javax.swing.JTextField();
        editJRDNC4 = new javax.swing.JTextField();
        editRELP_SAVE = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        editPILLOUT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit relationship details");
        setResizable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));

        RDNCD_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNCD_L.setText("Number of children");

        editJRDNMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJRDNMNActionPerformed(evt);
            }
        });
        editJRDNMN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJRDNMNKeyTyped(evt);
            }
        });

        RDNK_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNK_L.setText("Name of next of kin");

        RDNRAS_L1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RDNRAS_L1.setText("Current Residential Address");

        RDNNBS_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNNBS_L.setText("Nearest bus stop");

        RDNC1_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC1_L.setText("Name of Child 1");

        RDDOB3_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB3_L.setText("Date of birth child 3");

        editJRDSC1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        RDNON_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNON_L.setText("Other numbers");

        editJRDDOB2.setDateFormatString("yyyy-MM-dd ");

        editJRDST.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abia ", "Adamawa ", "Akwa Ibom ", "FCT  Abuja", "Anambra ", "Bauchi ", "Bayelsa ", "Benue ", "Borno ", "Cross River ", "Delta ", "Ebonyi", "Edo ", "Ekiti ", "Enugu ", "Gombe", "Imo ", "Jigawa ", "Kaduna", "Kano ", "Katsina ", "Kebbi ", "Kogi ", "Kwara ", "Lagos ", "Nasarawa ", "Ogun ", "Ondo ", "Osun ", "Oyo", "Plateau ", "Rivers ", "Sokoto ", "Taraba", "Yobe", "Zamfara" }));

        RDIC_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDIC_L.setText("Person to Call in Emergency");

        editJRDSC4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        editJRDDOB3.setDateFormatString("yyyy-MM-dd ");

        editJRDSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJRDSIActionPerformed(evt);
            }
        });

        RDST_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDST_L.setText("State");

        RDNC3_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC3_L.setText("Name of child 3");

        editJRDIMN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJRDIMNKeyTyped(evt);
            }
        });

        RDLGA_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDLGA_L.setText("Local Govt. Area");

        RDNMN_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNMN_L.setText("Mobile number");

        RDDOB1_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB1_L.setText("Date of birth Child 1");

        editJRDNON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJRDNONActionPerformed(evt);
            }
        });
        editJRDNON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJRDNONKeyTyped(evt);
            }
        });

        RDNC4_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC4_L.setText("Name of child 4");

        RDNDOB_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNDOB_L.setText("Date of birth");

        RDNRAS_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNRAS_L.setText("Street number/ Street name");

        RDLNS_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDLNS_L.setText("Name of spouse");

        RDNG_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNG_L.setText("Gender");

        RDSC1_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC1_L.setText("Sex of child 1");

        editJRDANK.setColumns(20);
        editJRDANK.setRows(5);
        jScrollPane1.setViewportView(editJRDANK);

        RDDOB2_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB2_L.setText("Date of birth Child 2");

        editJRDMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJRDMPKeyTyped(evt);
            }
        });

        editJRDSC2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        editJDRDDOB1.setDateFormatString("yyyy-MM-dd ");

        RDNC2_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC2_L.setText("Name of Child 2");

        editJRDNG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        RDSC3_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC3_L.setText("Sex of chld 3");

        editJRDNDOB.setDateFormatString("yyyy-MM-dd ");

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setText("EDIT RELATIONSHIP DETAILS");

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel2.setText("NEXT OF KIN INFORMATION");

        RDNCT_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNCT_L.setText("City / Town");

        editJRDDOB4.setDateFormatString("yyyy-MM-dd ");

        RDNC4_L3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC4_L3.setText("Address of next of kin");

        editJRDSC3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        RDSC4_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC4_L.setText("Sex of child 4");

        RDMP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDMP_L.setText("Mobile number");

        RDSC2_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC2_L.setText("Sex of child 2");

        RDNR_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNR_L.setText("Relationship");

        RDDOB4_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB4_L.setText("Date of birth child 4");

        RDIMN_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDIMN_L.setText("Mobile no");

        RDSI.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSI.setText("Staff ID");

        editJRDNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJRDNRActionPerformed(evt);
            }
        });

        editJRDNC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJRDNC4ActionPerformed(evt);
            }
        });

        editRELP_SAVE.setText("Save");
        editRELP_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRELP_SAVEActionPerformed(evt);
            }
        });

        jButton2.setText("home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        editPILLOUT.setText("eXIT");
        editPILLOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPILLOUTActionPerformed(evt);
            }
        });

        jButton4.setText("back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RDNK_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editJRDNK, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RDNCD_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editJRDNCD, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RDMP_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editJRDMP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDNC1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNC2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNC4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDNC1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDNC2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDNC3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDNC4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editJRDDOB4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RDDOB2_L, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(RDDOB3_L, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(RDDOB4_L, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(RDDOB1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editJDRDDOB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editJRDDOB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editJRDDOB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RDSC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RDSC2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RDSC4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editJRDSC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editJRDSC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editJRDSC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editJRDSC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(RDSC1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(RDNRAS_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RDNDOB_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDNC4_L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDNR_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDNMN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(editJRDNR, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editJRDNDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(editJRDNMN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RDLGA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(editJRDLGA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RDNG_L, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RDNON_L, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editJRDNON, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editJRDNG, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(RDNCT_L, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(editJRDNCT, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(RDNNBS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editJRDNNBS))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(RDNRAS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editJRDNRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(RDIMN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editJRDIMN))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RDST_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RDIC_L))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editJRDIC, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editJRDST, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RDSI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDLNS_L, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editJRDLNS)
                            .addComponent(editJRDSI)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(editRELP_SAVE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(editPILLOUT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(RDSC1_L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editJRDSC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RDSI)
                                    .addComponent(editJRDSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RDLNS_L)
                                            .addComponent(editJRDLNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RDMP_L)
                                            .addComponent(editJRDMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RDNCD_L)
                                            .addComponent(editJRDNCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RDNC1_L)
                                        .addGap(8, 8, 8)
                                        .addComponent(editJRDNC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(RDDOB1_L)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editJDRDDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RDDOB2_L)
                                    .addComponent(RDSC2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RDNC2_L))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editJRDNC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editJRDDOB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(editJRDSC2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RDNC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RDDOB3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(RDSC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editJRDNC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDDOB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDSC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDSC4_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RDNC4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RDDOB4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editJRDNC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDSC4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(editJRDDOB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RDNK_L)
                    .addComponent(editJRDNK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RDNC4_L3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RDNDOB_L)
                                .addComponent(RDNG_L)
                                .addComponent(editJRDNG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editJRDNDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDNR_L)
                            .addComponent(editJRDNR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDNMN_L)
                            .addComponent(RDNON_L)
                            .addComponent(editJRDNMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editJRDNON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RDNRAS_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDNRAS_L)
                            .addComponent(editJRDNRAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNCT_L)
                            .addComponent(editJRDNCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDNNBS_L)
                            .addComponent(editJRDNNBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDLGA_L)
                            .addComponent(editJRDLGA_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDST_L)
                            .addComponent(editJRDST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDIC_L)
                            .addComponent(editJRDIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDIMN_L)
                            .addComponent(editJRDIMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editRELP_SAVE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(editPILLOUT))
                .addGap(101, 101, 101))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editJRDNMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJRDNMNActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editJRDNMNActionPerformed

    private void editJRDNMNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJRDNMNKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c1 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c1) || (c1 == KeyEvent.VK_BACKSPACE ) || c1 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editJRDNMNKeyTyped

    private void editJRDSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJRDSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJRDSIActionPerformed

    private void editJRDIMNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJRDIMNKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c12 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c12) || (c12 == KeyEvent.VK_BACKSPACE ) || c12 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editJRDIMNKeyTyped

    private void editJRDNONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJRDNONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJRDNONActionPerformed

    private void editJRDNONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJRDNONKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c11 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c11) || (c11 == KeyEvent.VK_BACKSPACE ) || c11 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editJRDNONKeyTyped

    private void editJRDMPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJRDMPKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c13 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c13) || (c13 == KeyEvent.VK_BACKSPACE ) || c13 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editJRDMPKeyTyped

    private void editJRDNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJRDNRActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editJRDNRActionPerformed

    private void editJRDNC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJRDNC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJRDNC4ActionPerformed

    private void editRELP_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRELP_SAVEActionPerformed
        // checking if Staff ID textfield is empty and returning a mesage if it is empty
               
        if (editJRDSI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");
        }
        else {
                    
            try{

                //loading the driver
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("connection worked");

                //creating connection
                Connection newie3 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                PreparedStatement flexie2 = newie3.prepareStatement("select * from persl_ds where S_ID = ? ");

                //getting text (STaff ID) form Jtextfield
                flexie2.setString(1,  editJRDSI.getText());
                ResultSet rs = flexie2.executeQuery();
                JOptionPane.showMessageDialog(null , "checking Staff ID");

                if (rs.next()){
                    //confirming from datbase if user-given Staff Id exist
                    JOptionPane.showMessageDialog(null, "Staff ID Exists ");
                  String   value2 =  editJRDSI.getText();
               
                try{
                PreparedStatement stmttz = newie3.prepareStatement("update relp_ds set S_ID = ?, RDLNS = ?,RDMP = ?, RDNCD = ?,RDNC1 = ?,DRDDOB1 = ?,RDSC1 = ?,RDNC2 = ?,RDDOB2 = ?,"
                        + "RDSC2 = ?,RDNC3 = ?,RDDOB3 = ?,RDSC3 = ?,RDNC4 = ?,RDDOB4 = ?,RDSC4 = ?,RDNK = ?, RDANK = ?, RDNDOB = ?, RDNG = ?,RDNR = ?, RDNMN = ?, RDNON = ?,RDNRAS = ?, RDNNBS = ?,RDNCT = ?,RDLGA = ?, RDST = ?,RDIC = ?, RDIMN = ?"
    + " where S_ID = '"+value2+"' " );
                //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmttz.setString(1, editJRDSI.getText());
                stmttz.setString(2, editJRDLNS.getText());
                stmttz.setString(3, editJRDMP.getText());
                stmttz.setString(4, editJRDNCD.getText());
                stmttz.setString(5, editJRDNC1.getText());
                stmttz.setString(6, ((JTextField)editJDRDDOB1.getDateEditor().getUiComponent()).getText());
                stmttz.setString(7, (String) editJRDSC1.getSelectedItem());
                stmttz.setString(8, editJRDNC2.getText());
                stmttz.setString(9, ((JTextField)editJRDDOB2.getDateEditor().getUiComponent()).getText());
                stmttz.setString(10, (String) editJRDSC2.getSelectedItem());
                stmttz.setString(11, editJRDNC3.getText());
                stmttz.setString(12, ((JTextField)editJRDDOB3.getDateEditor().getUiComponent()).getText());
                stmttz.setString(13, (String) editJRDSC3.getSelectedItem());
                stmttz.setString(14, editJRDNC4.getText());
                stmttz.setString(15, ((JTextField)editJRDDOB4.getDateEditor().getUiComponent()).getText());
                stmttz.setString(16, (String) editJRDSC4.getSelectedItem());
                stmttz.setString(17, editJRDNK.getText());
                stmttz.setString(18, editJRDANK.getText());
                stmttz.setString(19, ((JTextField)editJRDNDOB.getDateEditor().getUiComponent()).getText());
                stmttz.setString(20, (String) editJRDNG.getSelectedItem());
                stmttz.setString(21, editJRDNR.getText());
                stmttz.setString(22, editJRDNMN.getText());
                stmttz.setString(23, editJRDNON.getText());
                stmttz.setString(24, editJRDNRAS.getText());
                stmttz.setString(25, editJRDNNBS.getText());
                stmttz.setString(26, editJRDNCT.getText());
                stmttz.setString(27, editJRDLGA_L.getText());
                stmttz.setString(28, (String) editJRDST.getSelectedItem());
                stmttz.setString(29, editJRDIC.getText());
                stmttz.setString(30, editJRDIMN.getText());

                 stmttz.execute();
                JOptionPane.showMessageDialog(rootPane, "relationship details updated ");
                editClear2();
                }catch (Exception ex){
                    ex.printStackTrace();
                }
                }
            }
            catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID" + "\n" + " SSand fill all the fields again");
            }
        }

    }//GEN-LAST:event_editRELP_SAVEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HOMAPAGE nm = new HOMAPAGE();
        nm.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editPILLOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPILLOUTActionPerformed
        // Exit form
        System.exit(0);
    }//GEN-LAST:event_editPILLOUTActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TO display EditREC window.
        this.dispose();
        EditREC nm = new EditREC();
        nm.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RDDOB1_L;
    private javax.swing.JLabel RDDOB2_L;
    private javax.swing.JLabel RDDOB3_L;
    private javax.swing.JLabel RDDOB4_L;
    private javax.swing.JLabel RDIC_L;
    private javax.swing.JLabel RDIMN_L;
    private javax.swing.JLabel RDLGA_L;
    private javax.swing.JLabel RDLNS_L;
    private javax.swing.JLabel RDMP_L;
    private javax.swing.JLabel RDNC1_L;
    private javax.swing.JLabel RDNC2_L;
    private javax.swing.JLabel RDNC3_L;
    private javax.swing.JLabel RDNC4_L;
    private javax.swing.JLabel RDNC4_L3;
    private javax.swing.JLabel RDNCD_L;
    private javax.swing.JLabel RDNCT_L;
    private javax.swing.JLabel RDNDOB_L;
    private javax.swing.JLabel RDNG_L;
    private javax.swing.JLabel RDNK_L;
    private javax.swing.JLabel RDNMN_L;
    private javax.swing.JLabel RDNNBS_L;
    private javax.swing.JLabel RDNON_L;
    private javax.swing.JLabel RDNRAS_L;
    private javax.swing.JLabel RDNRAS_L1;
    private javax.swing.JLabel RDNR_L;
    private javax.swing.JLabel RDSC1_L;
    private javax.swing.JLabel RDSC2_L;
    private javax.swing.JLabel RDSC3_L;
    private javax.swing.JLabel RDSC4_L;
    private javax.swing.JLabel RDSI;
    private javax.swing.JLabel RDST_L;
    private com.toedter.calendar.JDateChooser editJDRDDOB1;
    private javax.swing.JTextArea editJRDANK;
    private com.toedter.calendar.JDateChooser editJRDDOB2;
    private com.toedter.calendar.JDateChooser editJRDDOB3;
    private com.toedter.calendar.JDateChooser editJRDDOB4;
    private javax.swing.JTextField editJRDIC;
    private javax.swing.JTextField editJRDIMN;
    private javax.swing.JTextField editJRDLGA_L;
    private javax.swing.JTextField editJRDLNS;
    private javax.swing.JTextField editJRDMP;
    private javax.swing.JTextField editJRDNC1;
    private javax.swing.JTextField editJRDNC2;
    private javax.swing.JTextField editJRDNC3;
    private javax.swing.JTextField editJRDNC4;
    private javax.swing.JTextField editJRDNCD;
    private javax.swing.JTextField editJRDNCT;
    private com.toedter.calendar.JDateChooser editJRDNDOB;
    private javax.swing.JComboBox editJRDNG;
    private javax.swing.JTextField editJRDNK;
    private javax.swing.JTextField editJRDNMN;
    private javax.swing.JTextField editJRDNNBS;
    private javax.swing.JTextField editJRDNON;
    private javax.swing.JTextField editJRDNR;
    private javax.swing.JTextField editJRDNRAS;
    private javax.swing.JComboBox editJRDSC1;
    private javax.swing.JComboBox editJRDSC2;
    private javax.swing.JComboBox editJRDSC3;
    private javax.swing.JComboBox editJRDSC4;
    private javax.swing.JTextField editJRDSI;
    private javax.swing.JComboBox editJRDST;
    private javax.swing.JButton editPILLOUT;
    private javax.swing.JButton editRELP_SAVE;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
