
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TWS
 */
public class EditRN extends javax.swing.JFrame {
               public void editClear4(){
                      editJRSI.setText(null);
                      editJRR.setText(null);
                      editJRAD.setText(null);
                      editJRNL.setText(null);
               }
    /**
     * Creates new form EditRN
     */
    public EditRN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editClearRn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editJRAD = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        RR_L = new javax.swing.JLabel();
        UpdtPG = new javax.swing.JButton();
        RAD_L = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        RNL_L = new javax.swing.JLabel();
        editJRSI = new javax.swing.JTextField();
        editJRR = new javax.swing.JTextField();
        editJRNL = new javax.swing.JTextField();
        editSaveRn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit religion information");
        setResizable(false);

        editClearRn.setText("clear");
        editClearRn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClearRnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("EDIT RELIGION");

        editJRAD.setColumns(20);
        editJRAD.setRows(5);
        jScrollPane1.setViewportView(editJRAD);

        jLabel2.setText("Staff ID");

        RR_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RR_L.setText("Religion");

        UpdtPG.setText("back");
        UpdtPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdtPGActionPerformed(evt);
            }
        });

        RAD_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RAD_L.setText("Address of place of worship");

        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        RNL_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RNL_L.setText("Name of Leader");

        editSaveRn.setText("save");
        editSaveRn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveRnActionPerformed(evt);
            }
        });

        jButton2.setText("exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addComponent(editSaveRn)
                .addGap(18, 18, 18)
                .addComponent(editClearRn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdtPG, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RR_L, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RAD_L)
                            .addComponent(RNL_L, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editJRSI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addComponent(jScrollPane1)
                            .addComponent(editJRR, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editJRNL))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editJRSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RR_L)
                    .addComponent(editJRR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RAD_L))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editJRNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RNL_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSaveRn)
                    .addComponent(editClearRn)
                    .addComponent(jButton2)
                    .addComponent(UpdtPG)
                    .addComponent(jButton5))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editSaveRnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSaveRnActionPerformed
        // TODO add your handling code here:
        if (editJRSI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");

        }
        else {

            try{

                //loading the driver
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("connection worked");

                //creating connection
                Connection newie5 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                PreparedStatement flexie4 = newie5.prepareStatement("select * from persl_ds where S_ID = ? ");

                //getting text (STaff ID) form Jtextfield
                flexie4.setString(1,  editJRSI.getText());
                ResultSet rs = flexie4.executeQuery();
                JOptionPane.showMessageDialog(null , "checking Staff ID");

                if (rs.next()){
                    //confirming from datbase if user-given Staff Id exist
                    JOptionPane.showMessageDialog(null, "Staff ID Exists ");
                      String value4 = editJRSI.getText(); 
              
                        try {
                                                    
                PreparedStatement stmttz3 = newie5.prepareStatement("update rln_ds set S_ID = ?, RR = ? ,RAD = ?,RNL = ? "  + " where S_ID = '"+value4+"' " );
                //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmttz3.setString(1, editJRSI.getText());
                stmttz3.setString(2, editJRR.getText());
                stmttz3.setString(3, editJRAD.getText());
                stmttz3.setString(4, editJRNL.getText());

                stmttz3.addBatch();
                stmttz3.executeBatch();
                JOptionPane.showMessageDialog(rootPane, "employee RELIGIOUS information updated!");
                editClear4();
                        }catch(Exception ex){
                            ex.printStackTrace();
                        }
            }
            }
            catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID \n   and fill all the fields again");
                 editClear4();
            }
        }
    }//GEN-LAST:event_editSaveRnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TO exit application
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UpdtPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdtPGActionPerformed
        // TO return to update page
        
        this.dispose();
        EditREC nm = new EditREC();
        nm.show();
    }//GEN-LAST:event_UpdtPGActionPerformed

    private void editClearRnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClearRnActionPerformed
        // TO clear all swing controls on this form
              editClear4();
    }//GEN-LAST:event_editClearRnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TO display homepage of application
        this.dispose();
        HOMAPAGE nm = new HOMAPAGE();
        nm.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RAD_L;
    private javax.swing.JLabel RNL_L;
    private javax.swing.JLabel RR_L;
    private javax.swing.JButton UpdtPG;
    private javax.swing.JButton editClearRn;
    private javax.swing.JTextArea editJRAD;
    private javax.swing.JTextField editJRNL;
    private javax.swing.JTextField editJRR;
    private javax.swing.JTextField editJRSI;
    private javax.swing.JButton editSaveRn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
