/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author TWS
 */
public class EditPD extends javax.swing.JFrame {
      public void Clearedit(){
          editPDS_ID.setText(null);
         editPDLN.setText(null);
         editPDFN.setText(null);
         editPDMN.setText(null);
         editPDDOB.setDate(null);
         editPDPB.setText(null);
         editPDMS.setSelectedItem(null);
         editPDG.setSelectedItem(null);
         editPDRS.setText(null);
         editPDBS.setText(null);
         editPDCT.setText(null);
         editPDLG.setText(null);
         editPDST.setSelectedItem(null);
         editPDMNO.setText(null);
         editPDON.setText(null); 
         editPDEA.setText(null);
         editPDSO.setSelectedItem(null);
         editPDSL.setText(null);
        
     }    
    
    
    
    /**
     * Creates new form EditPD
     */
    public EditPD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editPDST = new javax.swing.JComboBox();
        editPDMNO = new javax.swing.JTextField();
        PDSO_L = new javax.swing.JLabel();
        editPDEA = new javax.swing.JTextField();
        PDEA_L = new javax.swing.JLabel();
        editPDSO = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        editJSBPD = new javax.swing.JButton();
        editjButton2 = new javax.swing.JButton();
        editjButton3 = new javax.swing.JButton();
        PDL = new javax.swing.JLabel();
        editPDS_ID = new javax.swing.JTextField();
        PDFN_L = new javax.swing.JLabel();
        editPDFN = new javax.swing.JTextField();
        PDSID_L = new javax.swing.JLabel();
        editPDMN = new javax.swing.JTextField();
        PDLN_L1 = new javax.swing.JLabel();
        editPDLN = new javax.swing.JTextField();
        PDDOB_L = new javax.swing.JLabel();
        PDMN_L1 = new javax.swing.JLabel();
        editPDPB = new javax.swing.JTextField();
        editPDDOB = new com.toedter.calendar.JDateChooser();
        PDG_L = new javax.swing.JLabel();
        editPDRS = new javax.swing.JTextField();
        PDMS_L = new javax.swing.JLabel();
        editPDMS = new javax.swing.JComboBox();
        PDPB_L = new javax.swing.JLabel();
        editPDCT = new javax.swing.JTextField();
        PDRS_L = new javax.swing.JLabel();
        editPDG = new javax.swing.JComboBox();
        PDLG_L = new javax.swing.JLabel();
        editPDBS = new javax.swing.JTextField();
        PDMN_L = new javax.swing.JLabel();
        editPDLG = new javax.swing.JTextField();
        PDON_L = new javax.swing.JLabel();
        editPDON = new javax.swing.JTextField();
        PDCT_L = new javax.swing.JLabel();
        editPDSL = new javax.swing.JTextField();
        PDST_L = new javax.swing.JLabel();
        PDBS_L = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Personal details");
        setResizable(false);

        editPDST.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abia ", "Adamawa ", "Akwa Ibom ", "Anambra ", "Bauchi ", "Bayelsa ", "Benue ", "Borno ", "Cross River ", "Delta ", "Ebonyi", "Edo ", "Ekiti ", "Enugu ", "Federal Capital Territory\tAbuja", "Gombe", "Imo ", "Jigawa ", "Kaduna", "Kano ", "Katsina ", "Kebbi ", "Kogi ", "Kwara ", "Lagos ", "Nasarawa ", "Ogun ", "Ondo ", "Osun ", "Oyo", "Plateau ", "Rivers ", "Sokoto ", "Taraba", "Yobe", "Zamfara" }));

        editPDMNO.setColumns(16);
        editPDMNO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        editPDMNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPDMNOActionPerformed(evt);
            }
        });
        editPDMNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editPDMNOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editPDMNOKeyTyped(evt);
            }
        });

        PDSO_L.setText("State of origin");

        PDEA_L.setText("e-mail");

        editPDSO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abia ", "Adamawa ", "Akwa Ibom ", "Anambra ", "Bauchi ", "Bayelsa ", "Benue ", "Borno ", "Cross River ", "Delta ", "Ebonyi", "Edo ", "Ekiti ", "Enugu ", "Federal Capital Territory\tAbuja", "Gombe", "Imo ", "Jigawa ", "Kaduna", "Kano ", "Katsina ", "Kebbi ", "Kogi ", "Kwara ", "Lagos ", "Nasarawa ", "Ogun ", "Ondo ", "Osun ", "Oyo", "Plateau ", "Rivers ", "Sokoto ", "Taraba", "Yobe", "Zamfara" }));

        jLabel3.setText("Local Government");

        editJSBPD.setText("save");
        editJSBPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJSBPDActionPerformed(evt);
            }
        });

        editjButton2.setText("clear");
        editjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton2ActionPerformed(evt);
            }
        });

        editjButton3.setText("Exit");
        editjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton3ActionPerformed(evt);
            }
        });

        PDL.setFont(new java.awt.Font("Kalinga", 1, 24)); // NOI18N
        PDL.setText("EDIT PERSONAL DETAILS");

        editPDS_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPDS_IDActionPerformed(evt);
            }
        });
        editPDS_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editPDS_IDKeyReleased(evt);
            }
        });

        PDFN_L.setText("First Name");

        PDSID_L.setText("Staff ID");

        PDLN_L1.setText("Last Name");

        editPDLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPDLNActionPerformed(evt);
            }
        });

        PDDOB_L.setText("Date of Birth");

        PDMN_L1.setText("Middle Name");

        editPDPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPDPBActionPerformed(evt);
            }
        });

        editPDDOB.setDateFormatString("yyyy-MM-dd ");

        PDG_L.setText("Gender");

        PDMS_L.setText("Marital Status");

        editPDMS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Married", "Single", "divorced", " " }));

        PDPB_L.setText("Place of birth");

        PDRS_L.setText("Residential address");

        editPDG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        PDLG_L.setText("Local Govt.");

        PDMN_L.setText("Current mobile no");

        PDON_L.setText("Other number");

        editPDON.setColumns(16);
        editPDON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPDONActionPerformed(evt);
            }
        });
        editPDON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editPDONKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editPDONKeyTyped(evt);
            }
        });

        PDCT_L.setText("City / Town");

        PDST_L.setText("State");

        PDBS_L.setText("Nearest bus stop");

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PDFN_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PDDOB_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDMN_L1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDMS_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDPB_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDCT_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDST_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDMN_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDSO_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(PDSID_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PDRS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editPDSO, 0, 1, Short.MAX_VALUE)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editPDRS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(editPDPB)
                            .addComponent(editPDMS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDCT)
                            .addComponent(editPDMNO)
                            .addComponent(editPDST, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(editPDS_ID)
                            .addComponent(editPDFN)
                            .addComponent(editPDMN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PDLN_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PDG_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PDBS_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PDLG_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PDON_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editPDLN)
                    .addComponent(editPDG, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPDBS)
                    .addComponent(editPDLG)
                    .addComponent(editPDON)
                    .addComponent(editPDSL, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(PDL, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PDEA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editPDEA, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(editJSBPD)
                        .addGap(18, 18, 18)
                        .addComponent(editjButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editjButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(PDL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PDSID_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDFN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDLN_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDMN_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(editPDS_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PDDOB_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDPB_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PDG_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PDMS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editPDMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editPDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDRS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDBS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDCT_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDLG_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDST_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDMN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDON_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDMNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDEA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDSO_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPDSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(editPDDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editJSBPD)
                    .addComponent(editjButton2)
                    .addComponent(editjButton3)
                    .addComponent(jButton1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editPDMNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPDMNOActionPerformed
        // TODO add your handling code here//:
    }//GEN-LAST:event_editPDMNOActionPerformed

    private void editPDMNOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPDMNOKeyReleased
        // TODO add your handling code here:
        // CODE TO ENSURE THat the textfield does not take alphabet input
        /*  CODE NOT GOOD ENOUGH, IT CANNOT TAKE MORE THAN 10 DIGITS
        try {
            x = Integer.parseInt(PDMNO.getText());
        } catch (NumberFormatException nfe) {
            PDMNO.setText("");
        }*/
        //if (PDMNO.getText().length()>=15) {
            //    getToolkit().beep();
            //  evt.consume();
    }//GEN-LAST:event_editPDMNOKeyReleased

    private void editPDMNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPDMNOKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_editPDMNOKeyTyped

    private void editJSBPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJSBPDActionPerformed
        // TODO add your handling code here:
        //START  -->  codes to ensure no empty field before database insert
        if (editPDS_ID.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter staff ID");
        }
        else if (editPDLN.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter Lastname of employee");
        }
        else if (editPDFN.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Firstname of employee");
        }
        else {
            ////END  -->  codes to ensure no empty field before database insert

            //START --> new code to check if staff ID is existing

            try {
                //loading the driver
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("connection worked");

                //creating connection
                Connection ETnewie2 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                PreparedStatement ETflexie = ETnewie2.prepareStatement("select * from persl_ds where S_ID = ? ");

                //getting text (STaff ID) form Jtextfield
                ETflexie.setString(1,  editPDS_ID.getText());
                ResultSet rs = ETflexie.executeQuery();
                JOptionPane.showMessageDialog(null , "checking Staff ID");

                if (rs.next()){
                    JOptionPane.showMessageDialog(null, "Staff ID Exists");
                   
                    
                
                      //setting user input from swing controls to variable names
                   String value1 = editPDS_ID.getText();
                 
      
                    //CODE TO INSERT VALUES NTO DATABASE
try{
                    //  SQL querry
                    PreparedStatement EDITstmtt1 = ETnewie2.prepareStatement("update persl_ds set S_ID = ?,L_N = ?,F_N = ?,M_N = ?,PD_D_O_B = ?,POB = ? ,M_S = ?,G_D = ?,RA = ?,NBS = ?,C_T = ?,LGA = ?,ST = ?,CMN = ?,CMON = ?,EM = ?,SOO = ?,LG = ? where S_ID = '"+value1+"' ");
                    
                    EDITstmtt1.setString(1, editPDS_ID.getText());
                    EDITstmtt1.setString(2, editPDLN.getText());
                    EDITstmtt1.setString(3, editPDFN.getText());
                    EDITstmtt1.setString(4, editPDMN.getText());
                    EDITstmtt1.setString(5, ((JTextField)editPDDOB.getDateEditor().getUiComponent()).getText());
                    EDITstmtt1.setString(6, editPDPB.getText());
                    EDITstmtt1.setString(7, (String) editPDMS.getSelectedItem());
                    EDITstmtt1.setString(8, (String) editPDG.getSelectedItem());
                    EDITstmtt1.setString(9, editPDRS.getText());
                    EDITstmtt1.setString(10, editPDBS.getText());
                    EDITstmtt1.setString(11, editPDCT.getText());
                    EDITstmtt1.setString(12, editPDLG.getText());
                    EDITstmtt1.setString(13, (String) editPDST.getSelectedItem());
                    EDITstmtt1.setString(14, editPDMNO.getText());
                    EDITstmtt1.setString(15, editPDON.getText());
                    EDITstmtt1.setString(16, editPDEA.getText());
                    EDITstmtt1.setString(17, (String) editPDSO.getSelectedItem());
                    EDITstmtt1.setString(18, editPDSL.getText());

                   
                    EDITstmtt1.execute();
                    JOptionPane.showMessageDialog(rootPane, "Employee data saved updated");
                    Clearedit();
      
} catch (Exception e){
    e.printStackTrace();
}
                }

            }

            catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(rootPane, "Error with STaff ID coding!!!");
                         e.printStackTrace();
            }
        }

    }//GEN-LAST:event_editJSBPDActionPerformed

    private void editjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton2ActionPerformed
        // TODO add your handling code here:
        Clearedit();
    }//GEN-LAST:event_editjButton2ActionPerformed

    private void editjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton3ActionPerformed
        // TODO add your handling code here:
        //code to exit GUI
        System.exit(0);
    }//GEN-LAST:event_editjButton3ActionPerformed

    private void editPDS_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPDS_IDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_editPDS_IDActionPerformed

    private void editPDS_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPDS_IDKeyReleased
        // TODO add your handling code here:
        //   na here
    }//GEN-LAST:event_editPDS_IDKeyReleased

    private void editPDLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPDLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPDLNActionPerformed

    private void editPDPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPDPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPDPBActionPerformed

    private void editPDONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPDONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPDONActionPerformed

    private void editPDONKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPDONKeyReleased
        // TODO add your handling code here:
        // CODE TO ENSURE THat the textfield does not take alphabet input
        /*    try {
            zz = Integer.parseInt(PDON.getText());
        } catch (NumberFormatException nfe) {
            PDON.setText("");
        }*/
        //  if (PDON.getText().length()>=15) {
            //   getToolkit().beep();
            //  evt.consume();
            //}
    }//GEN-LAST:event_editPDONKeyReleased

    private void editPDONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPDONKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char cc =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(cc) || (cc == KeyEvent.VK_BACK_SPACE ) || cc == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editPDONKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EditREC nm = new EditREC();
        nm.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PDBS_L;
    private javax.swing.JLabel PDCT_L;
    private javax.swing.JLabel PDDOB_L;
    private javax.swing.JLabel PDEA_L;
    private javax.swing.JLabel PDFN_L;
    private javax.swing.JLabel PDG_L;
    private javax.swing.JLabel PDL;
    private javax.swing.JLabel PDLG_L;
    private javax.swing.JLabel PDLN_L1;
    private javax.swing.JLabel PDMN_L;
    private javax.swing.JLabel PDMN_L1;
    private javax.swing.JLabel PDMS_L;
    private javax.swing.JLabel PDON_L;
    private javax.swing.JLabel PDPB_L;
    private javax.swing.JLabel PDRS_L;
    private javax.swing.JLabel PDSID_L;
    private javax.swing.JLabel PDSO_L;
    private javax.swing.JLabel PDST_L;
    private javax.swing.JButton editJSBPD;
    private javax.swing.JTextField editPDBS;
    private javax.swing.JTextField editPDCT;
    private com.toedter.calendar.JDateChooser editPDDOB;
    private javax.swing.JTextField editPDEA;
    private javax.swing.JTextField editPDFN;
    private javax.swing.JComboBox editPDG;
    private javax.swing.JTextField editPDLG;
    private javax.swing.JTextField editPDLN;
    private javax.swing.JTextField editPDMN;
    private javax.swing.JTextField editPDMNO;
    private javax.swing.JComboBox editPDMS;
    private javax.swing.JTextField editPDON;
    private javax.swing.JTextField editPDPB;
    private javax.swing.JTextField editPDRS;
    private javax.swing.JTextField editPDSL;
    private javax.swing.JComboBox editPDSO;
    private javax.swing.JComboBox editPDST;
    private javax.swing.JTextField editPDS_ID;
    private javax.swing.JButton editjButton2;
    private javax.swing.JButton editjButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
