

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TWS
 */
public class EditFD extends javax.swing.JFrame {
                public void editClear3(){
                    editJFDSI.setText(null);
                    editJFDNP.setText(null);
                    editJFDAP.setText(null);
                    editJFDQ.setSelectedItem(null);
                    editJFDAOP.setText(null);
                }         
                
    /**
     * Creates new form EditFD
     */
    public EditFD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FDAP_L = new javax.swing.JLabel();
        FDQ_L = new javax.swing.JLabel();
        FDAOP_L = new javax.swing.JLabel();
        editjButton2 = new javax.swing.JButton();
        editThroway = new javax.swing.JButton();
        editJFDSI = new javax.swing.JTextField();
        editJFDNP = new javax.swing.JTextField();
        editjLabel1 = new javax.swing.JLabel();
        editJFDAP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editJFDQ = new javax.swing.JComboBox();
        FDNP_L = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editJFDAOP = new javax.swing.JTextArea();
        editFam_Save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Family details");
        setResizable(false);

        FDAP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDAP_L.setText("Address of parents");

        FDQ_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDQ_L.setText("Are they living together?");

        FDAOP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDAOP_L.setText("If no, state other address");

        editjButton2.setText("clear");
        editjButton2.setToolTipText("click to clear data in all the fields");
        editjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton2ActionPerformed(evt);
            }
        });

        editThroway.setText("Exit");
        editThroway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editThrowayActionPerformed(evt);
            }
        });

        editJFDNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJFDNPActionPerformed(evt);
            }
        });

        editjLabel1.setFont(new java.awt.Font("DokChampa", 1, 24)); // NOI18N
        editjLabel1.setText("Edit Family Details");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Staff ID");

        editJFDQ.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        editJFDQ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        editJFDQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJFDQActionPerformed(evt);
            }
        });

        FDNP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDNP_L.setText("Name of parents");

        editJFDAOP.setColumns(20);
        editJFDAOP.setRows(5);
        jScrollPane2.setViewportView(editJFDAOP);

        editFam_Save.setText("save");
        editFam_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFam_SaveActionPerformed(evt);
            }
        });

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editFam_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editjButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editThroway)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FDNP_L, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FDQ_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FDAP_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FDAOP_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editJFDSI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editJFDQ, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editJFDNP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editJFDAP, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(editjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editJFDSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDNP_L)
                    .addComponent(editJFDNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDAP_L)
                    .addComponent(editJFDAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDQ_L)
                    .addComponent(editJFDQ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FDAOP_L)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editFam_Save)
                    .addComponent(editjButton2)
                    .addComponent(editThroway)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton2ActionPerformed
        // clear all fields
        editClear3();
    }//GEN-LAST:event_editjButton2ActionPerformed

    private void editThrowayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editThrowayActionPerformed
        // code to exit windows
        System.exit(0);
    }//GEN-LAST:event_editThrowayActionPerformed

    private void editJFDNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJFDNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJFDNPActionPerformed

    private void editJFDQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJFDQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJFDQActionPerformed

    private void editFam_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFam_SaveActionPerformed
        // saving family details to database
        if (editJFDSI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");

        }
        else {

            try{

                //loading the driver
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("connection worked");

                //creating connection
                Connection editnewie4 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                PreparedStatement editflexie3 = editnewie4.prepareStatement("select * from persl_ds where S_ID = ? ");

                //getting text (STaff ID) form Jtextfield
                //confirming from datbase if user-given Staff Id exist
                editflexie3.setString(1,  editJFDSI.getText());
                ResultSet rs = editflexie3.executeQuery();
                JOptionPane.showMessageDialog(null , "checking Staff ID");

                if (rs.next()){
                    //display message confirming from datbase that user-given Staff Id exist
                    JOptionPane.showMessageDialog(null, "Staff ID Exists ");
                           
                    //Instantiating "value3"
                    String value3 = editJFDSI.getText();

                try{

                PreparedStatement editstmttz2 = editnewie4.prepareStatement("update fam_ds set S_ID = ?, FDNP = ?, FDAP = ?, FDQ = ?, FDAOP = ?"
                    + "where S_ID = '"+value3+"'  ");
                //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                editstmttz2.setString(1, editJFDSI.getText());
                editstmttz2.setString(2, editJFDNP.getText());
                editstmttz2.setString(3, editJFDAP.getText());
                editstmttz2.setString(4, (String) editJFDQ.getSelectedItem());
                editstmttz2.setString(5, editJFDAOP.getText());

                
                editstmttz2.execute();
                JOptionPane.showMessageDialog(rootPane, "new employee FAMILY information saved!");
               editClear3();;
                 
                }catch (Exception ex){
                    ex.printStackTrace();
                }
                }
            }
            catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID \n   and fill all the fields again");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_editFam_SaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TO display Update page
        this.dispose();
        EditREC nm = new EditREC();
        nm.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FDAOP_L;
    private javax.swing.JLabel FDAP_L;
    private javax.swing.JLabel FDNP_L;
    private javax.swing.JLabel FDQ_L;
    private javax.swing.JButton editFam_Save;
    private javax.swing.JTextArea editJFDAOP;
    private javax.swing.JTextField editJFDAP;
    private javax.swing.JTextField editJFDNP;
    private javax.swing.JComboBox editJFDQ;
    private javax.swing.JTextField editJFDSI;
    private javax.swing.JButton editThroway;
    private javax.swing.JButton editjButton2;
    private javax.swing.JLabel editjLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
