
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import javax.swing.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TWS
 */
public class EditPE extends javax.swing.JFrame {
             public void    editClear5(){
                   editJEFSI.setText(null);
                   editJELN.setText(null);
                   editJELAD.setText(null);
                   editJELNB.setText(null);
                   editJELOCN.setText(null);
                   editJELPE.setSelectedItem(null);
                   editJELES.setDate(null);
                   editJELEE.setDate(null);
                   editJELSA.setText(null);
                   editJELSM.setText(null);
                   editJELPH.setText(null);
                   editJELRL.setText(null);
               }

    /**
     * Creates new form EditPE
     */
    public EditPE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editJELEE = new com.toedter.calendar.JDateChooser();
        editJELSA = new javax.swing.JTextField();
        editJELSM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editJELPH = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        editJELRL = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editPEMP_SAVE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editJELAD = new javax.swing.JTextArea();
        editjButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        editJELPE = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        editUP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        editJEFSI = new javax.swing.JTextField();
        editJELN = new javax.swing.JTextField();
        editJELNB = new javax.swing.JTextField();
        editJELOCN = new javax.swing.JTextField();
        editJELES = new com.toedter.calendar.JDateChooser();
        editPG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editJELEE.setDateFormatString("yyyy-MM-dd ");

        editJELSA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJELSAKeyTyped(evt);
            }
        });

        editJELSM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJELSMKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("EDIT PREVIOUS EMPLOYMENT");

        editJELPH.setColumns(20);
        editJELPH.setRows(5);
        jScrollPane2.setViewportView(editJELPH);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Staff ID");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Employer / Name of Company");

        editJELRL.setColumns(20);
        editJELRL.setRows(5);
        jScrollPane3.setViewportView(editJELRL);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Address of company");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Nature of business");

        editPEMP_SAVE.setText("save");
        editPEMP_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPEMP_SAVEActionPerformed(evt);
            }
        });

        editJELAD.setColumns(20);
        editJELAD.setRows(5);
        jScrollPane1.setViewportView(editJELAD);

        editjButton2.setText("clear");
        editjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Office contact number");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Period of employment start date");

        jLabel14.setText("Were you employed by the company directly ?");

        editJELPE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        editJELPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJELPEActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("period of employmen end date");

        editUP.setText("Home");
        editUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUPActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("last earned salary: Annual gross");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("last earned salary: Monthly pay");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("position held and responsibility");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Reason for leaving");

        editJELN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJELNActionPerformed(evt);
            }
        });

        editJELNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJELNBActionPerformed(evt);
            }
        });

        editJELOCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJELOCNActionPerformed(evt);
            }
        });
        editJELOCN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJELOCNKeyTyped(evt);
            }
        });

        editJELES.setDateFormatString("yyyy-MM-dd ");

        editPG.setText("back");
        editPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editPEMP_SAVE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1)
                                            .addComponent(editJELNB)
                                            .addComponent(editJELN)
                                            .addComponent(editJEFSI)
                                            .addComponent(editJELOCN)
                                            .addComponent(editJELES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(editJELEE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(editJELSA)
                                            .addComponent(editJELSM))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editJELPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editjButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(editUP)
                                .addGap(18, 18, 18)
                                .addComponent(editPG))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(editJEFSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(editJELN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editJELNB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editJELOCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(editJELES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel8))
                            .addComponent(editJELPE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(editJELEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editJELSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(editJELSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPEMP_SAVE)
                    .addComponent(editjButton2)
                    .addComponent(jButton3)
                    .addComponent(editUP)
                    .addComponent(editPG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editJELSAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJELSAKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char cc11 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(cc11) || (cc11 == KeyEvent.VK_BACKSPACE ) || cc11 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editJELSAKeyTyped

    private void editJELSMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJELSMKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char cc33 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(cc33) || (cc33 == KeyEvent.VK_BACKSPACE ) || cc33 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editJELSMKeyTyped

    private void editPEMP_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPEMP_SAVEActionPerformed
        if (editJEFSI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");
        }
        else if (editJELN.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter Lastname of employee");
        }
        else if (editJELAD.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Firstname of employee");
        }
        else {

            try{

                //loading the driver
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("connection worked");

                //creating connection
                Connection newie6 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                PreparedStatement flexie5 = newie6.prepareStatement("select * from persl_ds where S_ID = ? ");

                //getting text (STaff ID) form Jtextfield
                flexie5.setString(1,  editJEFSI.getText());
                ResultSet rs = flexie5.executeQuery();
                JOptionPane.showMessageDialog(null , "checking Staff ID");

                if (rs.next()){
                    //confirming from datbase if user-given Staff Id exist
                    JOptionPane.showMessageDialog(null, "Staff ID Exists ");
                    
                    //set value gotten from user to value5
                         String value5 = editJEFSI.getText();
               try{
                PreparedStatement stmttz4 = newie6.prepareStatement("update pel_ds set S_ID = ? ,ELN = ?, ELAD = ?,ELNB = ? ,ELOCN = ?,ELPE = ?,ELES = ?,ELEE = ?,ELSA = ?,ELSM = ?,ELPH = ?,ELRL = ?  "
                    + "where S_ID = '"+value5+"'   " );
                //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmttz4.setString(1, editJEFSI.getText());
                stmttz4.setString(2, editJELN.getText());
                stmttz4.setString(3, editJELAD.getText());
                stmttz4.setString(4, editJELNB.getText());
                stmttz4.setString(5, editJELOCN.getText());
                stmttz4.setString(6, (String) editJELPE.getSelectedItem());
                stmttz4.setString(7, ((JTextField)editJELES.getDateEditor().getUiComponent()).getText());
                stmttz4.setString(8, ((JTextField)editJELEE.getDateEditor().getUiComponent()).getText());
                stmttz4.setString(9, editJELSA.getText());
                stmttz4.setString(10, editJELSM.getText());
                stmttz4.setString(11, editJELPH.getText());
                stmttz4.setString(12, editJELRL.getText());

                stmttz4.execute();
                JOptionPane.showMessageDialog(rootPane, "employee previous employment details updated");
                  editClear5();
                }catch (Exception ex){
                        ex.printStackTrace();
                        }
                }
            }
            catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID \n  SSand fill all the fields again");
            }
        }

    }//GEN-LAST:event_editPEMP_SAVEActionPerformed

    private void editjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton2ActionPerformed
        // code to clear swing functions
        editClear5();
    }//GEN-LAST:event_editjButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // code to exit application
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void editJELPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJELPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJELPEActionPerformed

    private void editJELNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJELNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJELNActionPerformed

    private void editJELNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJELNBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJELNBActionPerformed

    private void editJELOCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJELOCNActionPerformed
        // CODE to ensure only numeric user input.

    }//GEN-LAST:event_editJELOCNActionPerformed

    private void editJELOCNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJELOCNKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char cc1 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(cc1) || (cc1 == KeyEvent.VK_BACKSPACE ) || cc1 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_editJELOCNKeyTyped

    private void editUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUPActionPerformed
        // TO display homepage 
         this.dispose();
        HOMAPAGE nm = new HOMAPAGE();
        nm.show();
    }//GEN-LAST:event_editUPActionPerformed

    private void editPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPGActionPerformed
        // TO display update page
        this.dispose();
        EditREC nm = new EditREC();
        nm.show();
    }//GEN-LAST:event_editPGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editJEFSI;
    private javax.swing.JTextArea editJELAD;
    private com.toedter.calendar.JDateChooser editJELEE;
    private com.toedter.calendar.JDateChooser editJELES;
    private javax.swing.JTextField editJELN;
    private javax.swing.JTextField editJELNB;
    private javax.swing.JTextField editJELOCN;
    private javax.swing.JComboBox editJELPE;
    private javax.swing.JTextArea editJELPH;
    private javax.swing.JTextArea editJELRL;
    private javax.swing.JTextField editJELSA;
    private javax.swing.JTextField editJELSM;
    private javax.swing.JButton editPEMP_SAVE;
    private javax.swing.JButton editPG;
    private javax.swing.JButton editUP;
    private javax.swing.JButton editjButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
