/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.*;
/**
 *
 * @author TWS
 */
public class EditES extends javax.swing.JFrame {
    
     //initialising the imageicon
                private ImageIcon immaaged2;
                
    //code to initialize the webcam    
        Webcam webcam = Webcam.getDefault();
      WebcamPanel panel = new WebcamPanel(webcam);
                
    // method to clear content of swing controls  
                 public void dele2(){
                         editJESSI.setText(null);
                         editJESSN.setText(null);
                         editJESGD.setSelectedItem(panel);
                         editJESDJ.setDate(null);
                         editJESPN.setText(null);
                         editJDEPTS.setText(null);
                         editJESDOB.setDate(null);
                         editJESCN.setText(null);
                         editJESRAD.setText(null);
                         editJESMHH.setText(null);
                         editJESPFA.setText(null);
                         editJESETD.setDate(null);
                     }    
                     
    /**
     * Creates new form EditES
     */
    public EditES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editJESPN = new javax.swing.JTextField();
        editJESGD = new javax.swing.JComboBox();
        editJDEPTS = new javax.swing.JTextField();
        editJESDOB = new com.toedter.calendar.JDateChooser();
        editJESCN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        editJESRAD = new javax.swing.JTextArea();
        editjLabel1 = new javax.swing.JLabel();
        editJESMHH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editJESPFA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editJESETD = new com.toedter.calendar.JDateChooser();
        editjButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        editclear_dele = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editjButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        editJESEP = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editjButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        editJESDJ = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editJESSI = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        editJESSN = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Employee Summary");
        setResizable(false);

        editJESGD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        editJESGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJESGDActionPerformed(evt);
            }
        });

        editJESDOB.setDateFormatString("yyyy-MM-dd ");

        editJESCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJESCNActionPerformed(evt);
            }
        });
        editJESCN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editJESCNKeyTyped(evt);
            }
        });

        editJESRAD.setColumns(20);
        editJESRAD.setRows(5);
        jScrollPane1.setViewportView(editJESRAD);

        editjLabel1.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        editjLabel1.setText("EDIT EMPLOYEE SUMMARY");

        editJESMHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJESMHHActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Staff ID");

        editJESPFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJESPFAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Staff Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Exit date");

        editJESETD.setDateFormatString("yyyy-MM-dd ");

        editjButton1.setText("save");
        editjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Gender");

        editclear_dele.setText("clear");
        editclear_dele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editclear_deleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Date Joined");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Position");

        editjButton4.setText("exit");
        editjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Department");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Date Of brth");

        editjButton8.setText("take photo");
        editjButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton8ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Contact number");

        editJESDJ.setDateFormatString(" yyyy-MM-dd");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Residential address");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("MHS Hospital");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("PFA");

        editJESSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJESSIActionPerformed(evt);
            }
        });

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editjButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(editclear_dele)))
                        .addGap(9, 9, 9)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editjButton4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(editJDEPTS, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(editjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(editJESSI, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editJESETD, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(editJESPFA, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(editJESMHH, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(editJESCN, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(editJESDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editjButton8)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 549, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editJESGD, 0, 135, Short.MAX_VALUE)
                                    .addComponent(editJESSN)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(editJESDJ, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(editJESPN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(editJESEP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(editJESEP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(editjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(editJESSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel7))
                                            .addComponent(editJESPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(editJDEPTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(editJESGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(editJESDJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(editJESSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editjButton8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))
                            .addComponent(editJESDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editJESCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editJESMHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editJESPFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(12, 12, 12)
                        .addComponent(editJESETD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editjButton4)
                    .addComponent(editjButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editclear_dele)
                        .addComponent(jButton1)))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editJESCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJESCNActionPerformed
        // TODO add your handling code here:
        editJESCN.setBackground(Color.ORANGE);
    }//GEN-LAST:event_editJESCNActionPerformed

    private void editJESCNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editJESCNKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c6 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c6) || (c6 == KeyEvent.VK_BACKSPACE ) || c6 == KeyEvent.VK_DELETE)){
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_editJESCNKeyTyped

    private void editJESMHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJESMHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJESMHHActionPerformed

    private void editJESPFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJESPFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJESPFAActionPerformed

    private void editjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton1ActionPerformed
        //converting the buffered image to binary inputstream
        FileInputStream fis = null;
        File file1 = new File("test.png");
        try {
            fis = new FileInputStream(file1);
            JOptionPane.showMessageDialog(rootPane, "loading worked");
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }

        if (editJESSI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");
            editJESSI.setText(null);
        }
        else {

            try{

                //loading the driver
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("connection worked");

                //creating connection
                Connection newie7 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                PreparedStatement flexie6 = newie7.prepareStatement("select * from persl_ds where S_ID = ? ");

                //getting text (STaff ID) form Jtextfield to search database
                flexie6.setString(1,  editJESSI.getText());
                ResultSet rs = flexie6.executeQuery();
                JOptionPane.showMessageDialog(null , "checking Staff ID");
                if (rs.next()){

                    //confirming from datbase if user-given Staff Id exist
                    JOptionPane.showMessageDialog(null, "Staff ID Exists ");
                     
                    // Settin
                     String value7 = editJESSI.getText();  

                try{

                PreparedStatement stmttz5 = newie7.prepareStatement("update emp_sum  set S_ID = ?,JESSN = ?,ESEP = ?,ESGD = ?,ESDJ = ?,ESPN = ?,DEPTS = ?,ESDOB = ?,ESCN = ?,"
                        + "ESRAD = ?,ESMHH = ?,ESPFA = ?,ESETD = ?  "
                     + "where S_ID = '"+value7+"'   " );
                //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmttz5.setString(1, editJESSI.getText());
                stmttz5.setString(2, editJESSN.getText());
                stmttz5.setBinaryStream(3, fis, (int)( file1.length()));
                stmttz5.setString(4, (String) editJESGD.getSelectedItem());
                stmttz5.setString(5, (String)  ((JTextField)editJESDJ.getDateEditor().getUiComponent()).getText());
                stmttz5.setString(6, editJESPN.getText());
                stmttz5.setString(7, editJDEPTS.getText());
                stmttz5.setString(8, (String)  ((JTextField)editJESDOB.getDateEditor().getUiComponent()).getText());
                stmttz5.setString(9, editJESCN.getText());
                stmttz5.setString(10, editJESRAD.getText());
                stmttz5.setString(11, editJESMHH.getText());
                stmttz5.setString(12, editJESPFA.getText());
                stmttz5.setString(13, (String)  ((JTextField)editJESETD.getDateEditor().getUiComponent()).getText());

                stmttz5.addBatch();
                int i = stmttz5.executeUpdate();
                if(i > -1)
                {
                    JOptionPane.showMessageDialog(rootPane, "Employee data updated");
                } 
                } catch(Exception e){
                        e.printStackTrace();
                        }
                }
            }  catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID" + "\n" + "and fill all the fields again");
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_editjButton1ActionPerformed

    private void editclear_deleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editclear_deleActionPerformed
        // method to clear swing controls
        dele2();
    }//GEN-LAST:event_editclear_deleActionPerformed

    private void editjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton4ActionPerformed
        // Code to exit system
        webcam.close();
        System.exit(0);

    }//GEN-LAST:event_editjButton4ActionPerformed

    private void editjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton8ActionPerformed
        //get default webcam and open
        webcam.open();
        // webcam.setViewSize(WebcamResolution.VGA.getSize());

        //setting webpanel display properties
        panel.setFPSDisplayed(true);
        panel.setDisplayDebugInfo(true);
        panel.setImageSizeDisplayed(true);
        panel.setMirrored(true);
        panel.setFillArea(true);

        BufferedImage image1 = webcam.getImage();

        //get image
        try {
            ImageIO.write(image1, "PNG", new File("test.png"));

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "This one na gobe");

        }

        //setting buffered image to imageicon
        immaaged2 = new ImageIcon(image1);

        //setting imageicon to Jlabel
        editJESEP.setIcon(immaaged2);
    }//GEN-LAST:event_editjButton8ActionPerformed

    private void editJESSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJESSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJESSIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TO open man edit menu:
        this.dispose();
        EditREC nm = new EditREC();
        nm.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editJESGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJESGDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJESGDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editJDEPTS;
    private javax.swing.JTextField editJESCN;
    private com.toedter.calendar.JDateChooser editJESDJ;
    private com.toedter.calendar.JDateChooser editJESDOB;
    private javax.swing.JLabel editJESEP;
    private com.toedter.calendar.JDateChooser editJESETD;
    private javax.swing.JComboBox editJESGD;
    private javax.swing.JTextField editJESMHH;
    private javax.swing.JTextField editJESPFA;
    private javax.swing.JTextField editJESPN;
    private javax.swing.JTextArea editJESRAD;
    private javax.swing.JTextField editJESSI;
    private javax.swing.JTextField editJESSN;
    private javax.swing.JButton editclear_dele;
    private javax.swing.JButton editjButton1;
    private javax.swing.JButton editjButton4;
    private javax.swing.JButton editjButton8;
    private javax.swing.JLabel editjLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
