
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TWS
 */
public class EmployeeSummary extends javax.swing.JFrame {
    
    //code to initialize the webcam    
        Webcam webcam = Webcam.getDefault();
      WebcamPanel panel = new WebcamPanel(webcam);
                
      //initialising the imageicon
                private ImageIcon immaaged1;
    
                // method to clear swing controls
        public void dele(){
            JESEP.setIcon(null);
            JESSI.setText(null);
            JESSN.setText(null);
            JESEP.setText(null);
            JESGD.setSelectedItem(null);
            JESDJ.setDate(null);
            JESPN.setText(null);
            JDEPTS.setText(null);
            JESDOB.setDate(null);
            JESCN.setText(null);
            JESRAD.setText(null);
            JESMHH.setText(null);
            JESPFA.setText(null); 
            JESETD.setDate(null);

        }
    /**
     * Creates new form EmployeeSummary
     */
    public EmployeeSummary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JESSI = new javax.swing.JTextField();
        JESSN = new javax.swing.JTextField();
        JESPN = new javax.swing.JTextField();
        JESGD = new javax.swing.JComboBox();
        JDEPTS = new javax.swing.JTextField();
        JESDOB = new com.toedter.calendar.JDateChooser();
        JESCN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JESRAD = new javax.swing.JTextArea();
        JESMHH = new javax.swing.JTextField();
        JESPFA = new javax.swing.JTextField();
        JESETD = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        clear_dele = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        JESEP = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        JESDJ = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Summary ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel1.setText("EMPLOYEE SUMMARY");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Staff ID");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Staff Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Exit date");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Date Joined");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Position");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Department");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Date Of brth");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Contact number");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Residential address");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("MHS Hospital");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("PFA");

        JESSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JESSIActionPerformed(evt);
            }
        });

        JESGD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        JESDOB.setDateFormatString("yyyy-MM-dd ");

        JESCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JESCNActionPerformed(evt);
            }
        });
        JESCN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JESCNKeyTyped(evt);
            }
        });

        JESRAD.setColumns(20);
        JESRAD.setRows(5);
        jScrollPane1.setViewportView(JESRAD);

        JESMHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JESMHHActionPerformed(evt);
            }
        });

        JESPFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JESPFAActionPerformed(evt);
            }
        });

        JESETD.setDateFormatString("yyyy-MM-dd ");

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        clear_dele.setText("clear");
        clear_dele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_deleActionPerformed(evt);
            }
        });

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("take photo");
        jButton6.setToolTipText("click to take photo from webcam");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        JESDJ.setDateFormatString(" yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JESMHH, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JESPFA, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JESETD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JESCN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JESDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDEPTS, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JESSN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JESPN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JESDJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(JESGD, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(JESSI, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(JESEP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(35, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6)
                                        .addGap(80, 80, 80))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(clear_dele)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(JESSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(JESSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(JESGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(JESDJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(JESPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(JESEP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(JDEPTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(JESDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JESCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JESMHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JESPFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(JESETD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(clear_dele)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JESSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JESSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JESSIActionPerformed

    private void JESMHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JESMHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JESMHHActionPerformed

    private void JESPFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JESPFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JESPFAActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           //get default webcam and open 
        webcam.open();
             // webcam.setViewSize(WebcamResolution.VGA.getSize());
             
        
         //setting webpanel display properties   
                panel.setFPSDisplayed(true);
		panel.setDisplayDebugInfo(true);
		panel.setImageSizeDisplayed(true);
		panel.setMirrored(true);
                panel.setFillArea(true);
            
                BufferedImage image1 = webcam.getImage();
        
//get image
       try {
              ImageIO.write(image1, "PNG", new File("test.png"));
              
              
               } catch (IOException ex) { 
                   JOptionPane.showMessageDialog(rootPane, "This one na gobe");
                   
               }
             
       
        //setting buffered image to imageicon
          immaaged1 = new ImageIcon(image1);
          
          //setting imageicon to Jlabel
           JESEP.setIcon(immaaged1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Code to exit system
        webcam.close();
        System.exit(0);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clear_deleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_deleActionPerformed
        // method to clear swing controls
        dele();
    }//GEN-LAST:event_clear_deleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //converting the buffered image to binary inputstream
          FileInputStream fis = null;
         File file1 = new File("test.png");
            try {
                fis = new FileInputStream(file1);
                JOptionPane.showMessageDialog(rootPane, "loading worked");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
        
        if (JESSI.getText().equals("")){
                  JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");
                 JESSI.setText(null);
            }
         else {
                          
         try{ 
             
              //loading the driver
                 Class.forName("com.mysql.jdbc.Driver"); 
                 System.out.print("connection worked");
                 
                 //creating connection
                Connection newie7 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                 PreparedStatement flexie6 = newie7.prepareStatement("select * from persl_ds where S_ID = ? ");
            
                 //getting text (STaff ID) form Jtextfield to search database
            flexie6.setString(1,  JESSI.getText());
             ResultSet rs = flexie6.executeQuery();
           JOptionPane.showMessageDialog(null , "checking Staff ID");
                  if (rs.next()){
         
         
           //confirming from datbase if user-given Staff Id exist
               JOptionPane.showMessageDialog(null, "Staff ID Exists ");
               
                       }
        //end --> new code to check if staff ID is existing
       
        // if staff ID is new , then NEXT STEP        
               else {
           JOptionPane.showMessageDialog(rootPane, "Please enter an existing Staff ID");
                  //this method deletes all characters in the swing controls to halt saving of data in database.            
                          dele();
              
       }
              
    PreparedStatement stmttz5 = newie7.prepareStatement("insert into emp_sum (S_ID,JESSN,ESEP,ESGD,ESDJ,ESPN,DEPTS,ESDOB,ESCN,ESRAD,ESMHH,ESPFA,ESETD )  "
                 + "values(?,?,?,?,?,?,?,?,?,?,?,?,?)" );
               //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmttz5.setString(1, JESSI.getText());
                stmttz5.setString(2, JESSN.getText());
                stmttz5.setBinaryStream(3, fis, (int)( file1.length()));
                stmttz5.setString(4, (String) JESGD.getSelectedItem());
                stmttz5.setString(5, (String)  ((JTextField)JESDJ.getDateEditor().getUiComponent()).getText());
                stmttz5.setString(6, JESPN.getText());
                stmttz5.setString(7, JDEPTS.getText());
                stmttz5.setString(8, (String)  ((JTextField)JESDOB.getDateEditor().getUiComponent()).getText());
                stmttz5.setString(9, JESCN.getText());
                stmttz5.setString(10, JESRAD.getText());
                stmttz5.setString(11, JESMHH.getText());
                stmttz5.setString(12, JESPFA.getText());
                stmttz5.setString(13, (String)  ((JTextField)JESETD.getDateEditor().getUiComponent()).getText());
                              
                
              
                
                stmttz5.addBatch();
                int i = stmttz5.executeUpdate();
			if(i > -1)
			{
				JOptionPane.showMessageDialog(rootPane, "Jesus Works");
                                
                        }
         }  catch (ClassNotFoundException | SQLException | HeadlessException e) {
                             JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID \n   and fill all the fields again");
                             e.printStackTrace();
                        }                                                
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JESCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JESCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JESCNActionPerformed

    private void JESCNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JESCNKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c6 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c6) || (c6 == KeyEvent.VK_BACKSPACE ) || c6 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_JESCNKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TO open Homepage
        this.dispose();
        InfoCat nm = new InfoCat();
        nm.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmployeeSummary().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JDEPTS;
    private javax.swing.JTextField JESCN;
    private com.toedter.calendar.JDateChooser JESDJ;
    private com.toedter.calendar.JDateChooser JESDOB;
    private javax.swing.JLabel JESEP;
    private com.toedter.calendar.JDateChooser JESETD;
    private javax.swing.JComboBox JESGD;
    private javax.swing.JTextField JESMHH;
    private javax.swing.JTextField JESPFA;
    private javax.swing.JTextField JESPN;
    private javax.swing.JTextArea JESRAD;
    private javax.swing.JTextField JESSI;
    private javax.swing.JTextField JESSN;
    private javax.swing.JButton clear_dele;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
