
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TWS
 */
public class FamlyDetails extends javax.swing.JFrame {
                        
    public void Clear3(){
        JFDSI.setText(null);
        JFDNP.setText(null);
        JFDAP.setText(null);
        JFDQ.setSelectedItem(null);
        JFDAOP.setText(null);
    }
    /**
     * Creates new form FamlyDetails
     */
    public FamlyDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FDNP_L = new javax.swing.JLabel();
        Fam_Save = new javax.swing.JButton();
        FDAP_L = new javax.swing.JLabel();
        FDQ_L = new javax.swing.JLabel();
        FDAOP_L = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Throway = new javax.swing.JButton();
        JFDSI = new javax.swing.JTextField();
        JFDNP = new javax.swing.JTextField();
        JFDAP = new javax.swing.JTextField();
        JFDQ = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        JFDAOP = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Family Details");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DokChampa", 1, 24)); // NOI18N
        jLabel1.setText("Family Details");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Staff ID");

        FDNP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDNP_L.setText("Name of parents");

        Fam_Save.setText("save");
        Fam_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fam_SaveActionPerformed(evt);
            }
        });

        FDAP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDAP_L.setText("Address of parents");

        FDQ_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDQ_L.setText("Are they living together?");

        FDAOP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FDAOP_L.setText("If no, state other address");

        jButton2.setText("clear");
        jButton2.setToolTipText("click to clear data in all the fields");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Throway.setText("Exit");
        Throway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThrowayActionPerformed(evt);
            }
        });

        JFDNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFDNPActionPerformed(evt);
            }
        });

        JFDQ.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JFDQ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        JFDQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFDQActionPerformed(evt);
            }
        });

        JFDAOP.setColumns(20);
        JFDAOP.setRows(5);
        jScrollPane2.setViewportView(JFDAOP);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fam_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Throway)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FDNP_L, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FDQ_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FDAP_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FDAOP_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JFDSI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFDQ, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFDNP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFDAP, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JFDSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDNP_L)
                    .addComponent(JFDNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDAP_L)
                    .addComponent(JFDAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDQ_L)
                    .addComponent(JFDQ, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FDAOP_L)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fam_Save)
                    .addComponent(jButton2)
                    .addComponent(Throway)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JFDQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFDQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFDQActionPerformed

    private void JFDNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFDNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFDNPActionPerformed

    private void ThrowayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThrowayActionPerformed
        // code to exit windows
       System.exit(0);
    }//GEN-LAST:event_ThrowayActionPerformed

    private void Fam_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fam_SaveActionPerformed
        // saving family details to database
        if (JFDSI.getText().equals("")){
                  JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");
                 
            }
         else {
                          
         try{ 
             
              //loading the driver
                 Class.forName("com.mysql.jdbc.Driver"); 
                 System.out.print("connection worked");
                 
                 //creating connection
                Connection newie4 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                 PreparedStatement flexie3 = newie4.prepareStatement("select * from persl_ds where S_ID = ? ");
            
                 //getting text (STaff ID) form Jtextfield
            flexie3.setString(1,  JFDSI.getText());
             ResultSet rs = flexie3.executeQuery();
           JOptionPane.showMessageDialog(null , "checking Staff ID");
            
       if (rs.next()){
           //confirming from datbase if user-given Staff Id exist
               JOptionPane.showMessageDialog(null, "Staff ID Exists ");
               
                       }
        //end --> new code to check if staff ID is existing
       
        // if staff ID is new , then NEXT STEP        
               else {
           JOptionPane.showMessageDialog(rootPane, "Please enter an existing Staff ID");
                                Clear3();
              
       }
              
    PreparedStatement stmttz2 = newie4.prepareStatement("insert into fam_ds(S_ID,FDNP,FDAP,FDQ,FDAOP )  "
                 + "values(?,?,?,?,?)" );
               //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmttz2.setString(1, JFDSI.getText());
                stmttz2.setString(2, JFDNP.getText());
                stmttz2.setString(3, JFDAP.getText());
                stmttz2.setString(4, (String) JFDQ.getSelectedItem());
                stmttz2.setString(5, JFDAOP.getText());
                              
                stmttz2.addBatch();
                stmttz2.executeBatch();
                JOptionPane.showMessageDialog(rootPane, "new employee FAMILY information saved!");
                Clear3();
                
                              }                                
                         catch (ClassNotFoundException | SQLException | HeadlessException e) {
                             JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID \n   and fill all the fields again");
                        }                                                
        }
    }//GEN-LAST:event_Fam_SaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // clear all fields
        Clear3();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TO open Religion page
        this.dispose();
        InfoCat nm = new InfoCat();
        nm.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamlyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamlyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamlyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamlyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamlyDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FDAOP_L;
    private javax.swing.JLabel FDAP_L;
    private javax.swing.JLabel FDNP_L;
    private javax.swing.JLabel FDQ_L;
    private javax.swing.JButton Fam_Save;
    private javax.swing.JTextArea JFDAOP;
    private javax.swing.JTextField JFDAP;
    private javax.swing.JTextField JFDNP;
    private javax.swing.JComboBox JFDQ;
    private javax.swing.JTextField JFDSI;
    private javax.swing.JButton Throway;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
