
import java.sql.*;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abubakar Emmanuel
 */
public class Login extends javax.swing.JDialog {
       Connection cornn = new DBConnection().connect();    
      
       //instantiating a method to make jcheckbox1 invisble at opening of the page
       public void messiie(){
           jCheckBox1.setVisible(false);
       }
    /**
     * Creates new form Login
     * @param parent
     * @param modal
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super (parent, modal);
        initComponents();
        setLocationRelativeTo(this);
       
       //using the method to hide the checkbox at the start of the page
       messiie();
           
     
          
       }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTL = new javax.swing.JLabel();
        LUN = new javax.swing.JLabel();
        LPD = new javax.swing.JLabel();
        LJTF = new javax.swing.JTextField();
        LJPD = new javax.swing.JPasswordField();
        LLB = new javax.swing.JButton();
        LEB = new javax.swing.JButton();
        CHECKB = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LTL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTL.setText("USER LOGIN");

        LUN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LUN.setText("Username");

        LPD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LPD.setText("Password");

        LJTF.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LJTFActionPerformed(evt);
            }
        });

        LJPD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LJPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LJPDActionPerformed(evt);
            }
        });

        LLB.setText("log in ");
        LLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLBActionPerformed(evt);
            }
        });

        LEB.setText("EXIT");
        LEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LEBActionPerformed(evt);
            }
        });

        CHECKB.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CHECKB.setText("show password");
        CHECKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKBActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBox1.setText("hide password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(LJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(LEB))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(LTL, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LPD, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(LJPD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(CHECKB))
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jCheckBox1))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(LLB))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LUN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(LJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(LEB))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LTL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(LPD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(LJPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(CHECKB))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jCheckBox1))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(LLB))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(LUN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LJTFActionPerformed

    private void LLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLBActionPerformed
        // TODO add your handling code here:
        String sql = "select * from log_in where USERNAME = ? and PASSD = ?";
        try{
            PreparedStatement spt = cornn.prepareStatement(sql);
            spt.setString(1,  LJTF.getText());
            spt.setString(2, LJPD.getText());
            ResultSet rs = spt.executeQuery();
            
            if (rs.next()){
                this.dispose();
                HOMAPAGE nm = new HOMAPAGE();
                nm.show();
            }
                else{
                        JOptionPane.showMessageDialog(null, "Username and password invalid");
                        }
            }
            catch (Exception e){
                
        }
    }//GEN-LAST:event_LLBActionPerformed

    private void LEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LEBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LEBActionPerformed

    private void LJPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LJPDActionPerformed
        // TODO add your handling code here:
       //THS CODE IS TO MAKE PASSWORDS INVISIBLE ---> LJPD.setEchoChar('*');
    
           // System.out.print("NAWAAAAAA");
        
       //}
    }//GEN-LAST:event_LJPDActionPerformed

    private void CHECKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKBActionPerformed
         //this is a code to unmask password
           LJPD.setEchoChar((char) 0);
           
         //setting the checkbox invisible after clicking
          CHECKB.setVisible(false);
          
          //displaying the next checkbox
           jCheckBox1.setVisible(true);
    }//GEN-LAST:event_CHECKBActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        //a code to mask password
        LJPD.setEchoChar('*');
        
        // this is to make the checkbox invisible after clicking
        jCheckBox1.setVisible(false);
        
        //this is to open the next checkbox
        CHECKB.setVisible(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
             
            Login dialog = new Login(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent e){
                    System.exit(0);
                }
            });
            
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CHECKB;
    private javax.swing.JButton LEB;
    private javax.swing.JPasswordField LJPD;
    private javax.swing.JTextField LJTF;
    private javax.swing.JButton LLB;
    private javax.swing.JLabel LPD;
    private javax.swing.JLabel LTL;
    private javax.swing.JLabel LUN;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
