
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//importing all the relevant packages needed in the app
/**
 *
 * @author Abubakar Emmanuel
 */
public class NewEmployee extends javax.swing.JFrame { 
    
        Webcam webcam = Webcam.getDefault();
      WebcamPanel panel = new WebcamPanel(webcam);
                
      //initialising the imageicon
                private ImageIcon immaaged1;
    
    //method to erase text from fields
    public void CLEAR(){
         eTFN.setText(null);
         eTLN.setText(null);
         JDC1.setIcon(null);
         eTAD.setText(null);
         eJML.setText(null);
         eLPX.setIcon(null);
         eTPH.setText(null);
         eTDP.setText(null);
         eFTMN.setText(null);
         eFTON.setText(null);
         eNFN.setText(null);
         eNTL.setText(null);
         eMLN.setText(null);
         eTNK.setText(null);
         eFMNN.setText(null); 
         eQCB.setSelectedItem(null);
         JDC2.setDate(null);
     }
    /**
     * Creates new form NewEmployee
     */
    public NewEmployee() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eLT = new javax.swing.JLabel();
        eLFN = new javax.swing.JLabel();
        eLLN = new javax.swing.JLabel();
        eLDB = new javax.swing.JLabel();
        eLAD = new javax.swing.JLabel();
        eLML = new javax.swing.JLabel();
        eTFN = new javax.swing.JTextField();
        eTLN = new javax.swing.JTextField();
        eTAD = new javax.swing.JTextField();
        eJML = new javax.swing.JTextField();
        eLQL = new javax.swing.JLabel();
        eQCB = new javax.swing.JComboBox();
        eLPX = new javax.swing.JLabel();
        eBPX = new javax.swing.JButton();
        eLPH = new javax.swing.JLabel();
        eTPH = new javax.swing.JTextField();
        eLDE = new javax.swing.JLabel();
        eLDT = new javax.swing.JLabel();
        eTDP = new javax.swing.JTextField();
        eLMN = new javax.swing.JLabel();
        eLON = new javax.swing.JLabel();
        eLNK = new javax.swing.JLabel();
        eNLN = new javax.swing.JLabel();
        eNTL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eNFN = new javax.swing.JTextField();
        eNMP = new javax.swing.JLabel();
        eNKA = new javax.swing.JLabel();
        eTNK = new javax.swing.JTextField();
        eSV = new javax.swing.JButton();
        eCLR = new javax.swing.JButton();
        eEXT = new javax.swing.JButton();
        eNKM = new javax.swing.JLabel();
        eMLN = new javax.swing.JTextField();
        BK = new javax.swing.JButton();
        JDC1 = new com.toedter.calendar.JDateChooser();
        JDC2 = new com.toedter.calendar.JDateChooser();
        eFTMN = new javax.swing.JFormattedTextField();
        eFTON = new javax.swing.JFormattedTextField();
        eFMNN = new javax.swing.JFormattedTextField();
        TEMP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eLT.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        eLT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eLT.setText("NEW EMPLOYEE");

        eLFN.setText("First name");

        eLLN.setText("Last name");

        eLDB.setText("Date of birth(DD-MM-YYYY)");

        eLAD.setText("Address");

        eLML.setText("e mail");

        eTFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTFNActionPerformed(evt);
            }
        });

        eTLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTLNActionPerformed(evt);
            }
        });

        eTAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTADActionPerformed(evt);
            }
        });

        eJML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJMLActionPerformed(evt);
            }
        });

        eLQL.setText("Qualification");

        eQCB.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        eQCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PHD", "BSc", "BSa", "HND", "OND", "SSCE" }));
        eQCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eQCBActionPerformed(evt);
            }
        });

        eBPX.setText("upload photo");
        eBPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBPXActionPerformed(evt);
            }
        });

        eLPH.setText("Post held");

        eTPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTPHActionPerformed(evt);
            }
        });

        eLDE.setText("Date of employment  (DMY)");

        eLDT.setText("Department");

        eTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTDPActionPerformed(evt);
            }
        });

        eLMN.setText("mobile no:");

        eLON.setText("other no:");

        eLNK.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        eLNK.setText("NEXT OF KIN INFORMATION");

        eNLN.setText("Last name");

        eNTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNTLActionPerformed(evt);
            }
        });

        jLabel2.setText("First Name");

        eNFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNFNActionPerformed(evt);
            }
        });

        eNMP.setText("mobile no:");

        eNKA.setText("Address");

        eTNK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTNKActionPerformed(evt);
            }
        });

        eSV.setText("Save");
        eSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSVActionPerformed(evt);
            }
        });

        eCLR.setText("Clear");
        eCLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCLRActionPerformed(evt);
            }
        });

        eEXT.setText("exit");
        eEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eEXTActionPerformed(evt);
            }
        });

        eNKM.setText("e mail");

        eMLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMLNActionPerformed(evt);
            }
        });

        BK.setText("back");
        BK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKActionPerformed(evt);
            }
        });

        JDC1.setDateFormatString("yyyy-MM-dd ");

        JDC2.setDateFormatString("yyyy-MM-dd");

        eFTMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eFTMNActionPerformed(evt);
            }
        });

        jLabel1.setText("Employee_id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eLMN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLPH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLLN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eLML, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eLFN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TEMP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 582, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(eFTMN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eLON, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(eTFN)
                                    .addComponent(eTLN)
                                    .addComponent(eTAD)
                                    .addComponent(eJML, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(eQCB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eTDP))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(eLPX, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eFTON, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JDC2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eTPH)
                                        .addGap(199, 199, 199)))
                                .addComponent(eBPX)
                                .addGap(114, 114, 114))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eNLN, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eNTL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eLNK, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eNKM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eMLN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eNFN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eNMP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eFMNN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eNKA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eTNK, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 129, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(BK)
                .addGap(18, 18, 18)
                .addComponent(eSV)
                .addGap(18, 18, 18)
                .addComponent(eCLR)
                .addGap(18, 18, 18)
                .addComponent(eEXT)
                .addGap(0, 326, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(eLT, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(eLT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(eTFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eLFN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eLLN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eTLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eLDB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eLAD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eTAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eJML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eLML, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eLQL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eQCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eLPH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eTPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eLDE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(eLPX, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(eBPX)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eLON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eLMN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(eFTMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eFTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(eLNK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNLN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTNK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNKA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eNKM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eMLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eNMP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eFMNN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BK)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eSV)
                        .addComponent(eCLR)
                        .addComponent(eEXT)))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eBPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBPXActionPerformed
        // TODO add your handling code here:
          //get default webcam and open 
        webcam.open();
             // webcam.setViewSize(WebcamResolution.VGA.getSize());
             
        
         //setting webpanel display properties   
                panel.setFPSDisplayed(true);
		panel.setDisplayDebugInfo(true);
		panel.setImageSizeDisplayed(true);
		panel.setMirrored(true);
                panel.setFillArea(true);
            
                BufferedImage image1 = webcam.getImage();
        
//get image
       try {
              ImageIO.write(image1, "PNG", new File("test.png"));
              
              
               } catch (IOException ex) { 
                   JOptionPane.showMessageDialog(rootPane, "This one na gobe");
                   
               }
             
       
        //setting buffered image to imageicon
          immaaged1 = new ImageIcon(image1);
          
          //setting imageicon to Jlabel
           eLPX.setIcon(immaaged1);
    }//GEN-LAST:event_eBPXActionPerformed

    private void eTPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTPHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTPHActionPerformed

    private void eTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTDPActionPerformed

    private void eNFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNFNActionPerformed

    private void eEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eEXTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_eEXTActionPerformed

    private void BKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKActionPerformed
        // TODO add your handling code here:
        this.dispose();
                HOMAPAGE nm = new HOMAPAGE();
                nm.show();
    }//GEN-LAST:event_BKActionPerformed

    private void eTFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTFNActionPerformed

    private void eTLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTLNActionPerformed

    private void eTADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTADActionPerformed

    private void eJMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eJMLActionPerformed

    private void eQCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eQCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eQCBActionPerformed

    private void eNTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNTLActionPerformed

    private void eMLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMLNActionPerformed

    private void eTNKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTNKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTNKActionPerformed

    private void eCLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCLRActionPerformed
        // TODO add your handling code here:
        CLEAR();
    }//GEN-LAST:event_eCLRActionPerformed

    private void eSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSVActionPerformed
        // TODO add your handling code here:         
         try {
                //loading the driver
                 Class.forName("com.mysql.jdbc.Driver"); 
                 System.out.print("connection worked");
                 //creating connection
                Connection connac = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                
                //  SQL querry
               
                PreparedStatement stmtt = connac.prepareStatement("insert into new_emp(EMP_ID, L_NM, F_NM, DOB, ADDR, E_MAIL, QUAL, POST_H, DATE_OF_EMP, DEPT,PHONE_NO,O_PHONE ,NEXT_FNM, NEXT_LNM, NEXT_MAIL, NEXT_ADD, NEXT_PHONE)  values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" );
                stmtt.setString(1, TEMP.getText());
                stmtt.setString(2, eTLN.getText());
                stmtt.setString(3, eTFN.getText());
                stmtt.setString(4, ((JTextField)JDC1.getDateEditor().getUiComponent()).getText());
                stmtt.setString(5, eTAD.getText());
                stmtt.setString(6, eJML.getText());
                stmtt.setString(7, (String) eQCB.getSelectedItem());
                stmtt.setString(8, eTPH.getText());
                stmtt.setString(9, ((JTextField)JDC2.getDateEditor().getUiComponent()).getText());
                stmtt.setString(10, eTDP.getText());
                stmtt.setString(11, eFTMN.getText());
                stmtt.setString(12, eFTON.getText());
                stmtt.setString(13, eNFN.getText());
                stmtt.setString(14, eNTL.getText());
                stmtt.setString(15, eMLN.getText());
                stmtt.setString(16, eTNK.getText());
                stmtt.setString(17, eFMNN.getText());
                
                stmtt.addBatch();
                stmtt.executeBatch();
                JOptionPane.showMessageDialog(rootPane, "employee data saved");
                CLEAR();
               
            }                   
                         catch (ClassNotFoundException | SQLException | HeadlessException e) {
                             JOptionPane.showMessageDialog(rootPane, "Error with coding!!!");
                             
                                          }
    }//GEN-LAST:event_eSVActionPerformed

    private void eFTMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eFTMNActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_eFTMNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BK;
    private com.toedter.calendar.JDateChooser JDC1;
    private com.toedter.calendar.JDateChooser JDC2;
    private javax.swing.JTextField TEMP;
    private javax.swing.JButton eBPX;
    private javax.swing.JButton eCLR;
    private javax.swing.JButton eEXT;
    private javax.swing.JFormattedTextField eFMNN;
    private javax.swing.JFormattedTextField eFTMN;
    private javax.swing.JFormattedTextField eFTON;
    private javax.swing.JTextField eJML;
    private javax.swing.JLabel eLAD;
    private javax.swing.JLabel eLDB;
    private javax.swing.JLabel eLDE;
    private javax.swing.JLabel eLDT;
    private javax.swing.JLabel eLFN;
    private javax.swing.JLabel eLLN;
    private javax.swing.JLabel eLML;
    private javax.swing.JLabel eLMN;
    private javax.swing.JLabel eLNK;
    private javax.swing.JLabel eLON;
    private javax.swing.JLabel eLPH;
    private javax.swing.JLabel eLPX;
    private javax.swing.JLabel eLQL;
    private javax.swing.JLabel eLT;
    private javax.swing.JTextField eMLN;
    private javax.swing.JTextField eNFN;
    private javax.swing.JLabel eNKA;
    private javax.swing.JLabel eNKM;
    private javax.swing.JLabel eNLN;
    private javax.swing.JLabel eNMP;
    private javax.swing.JTextField eNTL;
    private javax.swing.JComboBox eQCB;
    private javax.swing.JButton eSV;
    private javax.swing.JTextField eTAD;
    private javax.swing.JTextField eTDP;
    private javax.swing.JTextField eTFN;
    private javax.swing.JTextField eTLN;
    private javax.swing.JTextField eTNK;
    private javax.swing.JTextField eTPH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}