
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TWS
 */
public class PersonalDetails extends javax.swing.JFrame {

     int x;
     int zz;
    
     public void Clear(){
          PDS_ID.setText(null);
         PDLN.setText(null);
         PDFN.setText(null);
         PDMN.setText(null);
         PDDOB.setDate(null);
         PDPB.setText(null);
         PDMS.setSelectedItem(null);
         PDG.setSelectedItem(null);
         PDRS.setText(null);
         PDBS.setText(null);
         PDCT.setText(null);
         PDLG.setText(null);
         PDST.setSelectedItem(null);
         PDMNO.setText(null);
         PDON.setText(null); 
         PDEA.setText(null);
         PDSO.setSelectedItem(null);
         PDSL.setText(null);
        
     }
    /**
     * Creates new form PersonalDetails
     */
    public PersonalDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PDL = new javax.swing.JLabel();
        PDFN_L = new javax.swing.JLabel();
        PDSID_L = new javax.swing.JLabel();
        PDLN_L1 = new javax.swing.JLabel();
        PDDOB_L = new javax.swing.JLabel();
        PDMN_L1 = new javax.swing.JLabel();
        PDG_L = new javax.swing.JLabel();
        PDMS_L = new javax.swing.JLabel();
        PDPB_L = new javax.swing.JLabel();
        PDRS_L = new javax.swing.JLabel();
        PDLG_L = new javax.swing.JLabel();
        PDMN_L = new javax.swing.JLabel();
        PDON_L = new javax.swing.JLabel();
        PDCT_L = new javax.swing.JLabel();
        PDST_L = new javax.swing.JLabel();
        PDBS_L = new javax.swing.JLabel();
        PDSO_L = new javax.swing.JLabel();
        PDEA_L = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JSBPD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PDS_ID = new javax.swing.JTextField();
        PDFN = new javax.swing.JTextField();
        PDMN = new javax.swing.JTextField();
        PDLN = new javax.swing.JTextField();
        PDPB = new javax.swing.JTextField();
        PDDOB = new com.toedter.calendar.JDateChooser();
        PDRS = new javax.swing.JTextField();
        PDMS = new javax.swing.JComboBox();
        PDCT = new javax.swing.JTextField();
        PDG = new javax.swing.JComboBox();
        PDBS = new javax.swing.JTextField();
        PDLG = new javax.swing.JTextField();
        PDON = new javax.swing.JTextField();
        PDSL = new javax.swing.JTextField();
        PDST = new javax.swing.JComboBox();
        PDMNO = new javax.swing.JTextField();
        PDEA = new javax.swing.JTextField();
        PDSO = new javax.swing.JComboBox();
        ERR = new javax.swing.JLabel();
        PDnext = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Details form");
        setPreferredSize(new java.awt.Dimension(733, 650));
        setResizable(false);

        PDL.setFont(new java.awt.Font("Kalinga", 1, 24)); // NOI18N
        PDL.setText("PERSONAL DETAILS");

        PDFN_L.setText("First Name");

        PDSID_L.setText("Staff ID");

        PDLN_L1.setText("Last Name");

        PDDOB_L.setText("Date of Birth");

        PDMN_L1.setText("Middle Name");

        PDG_L.setText("Gender");

        PDMS_L.setText("Marital Status");

        PDPB_L.setText("Place of birth");

        PDRS_L.setText("Residential address");

        PDLG_L.setText("Local Govt.");

        PDMN_L.setText("Current mobile no");

        PDON_L.setText("Other number");

        PDCT_L.setText("City / Town");

        PDST_L.setText("State");

        PDBS_L.setText("Nearest bus stop");

        PDSO_L.setText("State of origin");

        PDEA_L.setText("e-mail");

        jLabel3.setText("Local Government");

        JSBPD.setText("save");
        JSBPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSBPDActionPerformed(evt);
            }
        });

        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        PDS_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDS_IDActionPerformed(evt);
            }
        });
        PDS_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PDS_IDKeyReleased(evt);
            }
        });

        PDLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDLNActionPerformed(evt);
            }
        });

        PDPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDPBActionPerformed(evt);
            }
        });

        PDDOB.setDateFormatString("yyyy-MM-dd ");

        PDMS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Married", "Single", "divorced", " " }));

        PDG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        PDON.setColumns(16);
        PDON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDONActionPerformed(evt);
            }
        });
        PDON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PDONKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PDONKeyTyped(evt);
            }
        });

        PDST.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abia ", "Adamawa ", "Akwa Ibom ", "Anambra ", "Bauchi ", "Bayelsa ", "Benue ", "Borno ", "Cross River ", "Delta ", "Ebonyi", "Edo ", "Ekiti ", "Enugu ", "Federal Capital Territory\tAbuja", "Gombe", "Imo ", "Jigawa ", "Kaduna", "Kano ", "Katsina ", "Kebbi ", "Kogi ", "Kwara ", "Lagos ", "Nasarawa ", "Ogun ", "Ondo ", "Osun ", "Oyo", "Plateau ", "Rivers ", "Sokoto ", "Taraba", "Yobe", "Zamfara" }));

        PDMNO.setColumns(16);
        PDMNO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PDMNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDMNOActionPerformed(evt);
            }
        });
        PDMNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PDMNOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PDMNOKeyTyped(evt);
            }
        });

        PDSO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abia ", "Adamawa ", "Akwa Ibom ", "Anambra ", "Bauchi ", "Bayelsa ", "Benue ", "Borno ", "Cross River ", "Delta ", "Ebonyi", "Edo ", "Ekiti ", "Enugu ", "Federal Capital Territory\tAbuja", "Gombe", "Imo ", "Jigawa ", "Kaduna", "Kano ", "Katsina ", "Kebbi ", "Kogi ", "Kwara ", "Lagos ", "Nasarawa ", "Ogun ", "Ondo ", "Osun ", "Oyo", "Plateau ", "Rivers ", "Sokoto ", "Taraba", "Yobe", "Zamfara" }));

        ERR.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        ERR.setText("please enter numbers only");

        PDnext.setText("back");
        PDnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDnextActionPerformed(evt);
            }
        });

        jButton4.setText("home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PDFN_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PDDOB_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDMN_L1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDMS_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDPB_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDCT_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDST_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDMN_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDSO_L, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(PDSID_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(PDRS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PDSO, 0, 1, Short.MAX_VALUE)
                                .addGap(164, 164, 164))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PDRS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(PDPB)
                                    .addComponent(PDMS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PDCT)
                                    .addComponent(PDMNO)
                                    .addComponent(PDST, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PDDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(PDS_ID)
                                    .addComponent(PDFN)
                                    .addComponent(PDMN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PDLN_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PDG_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PDBS_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PDLG_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PDON_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PDLN)
                            .addComponent(PDG, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDBS)
                            .addComponent(PDLG)
                            .addComponent(PDON)
                            .addComponent(PDSL, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(PDL, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PDEA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PDEA, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ERR, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JSBPD)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(PDnext)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(78, 78, 78)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(PDL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PDSID_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDFN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDLN_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDMN_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PDS_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PDDOB_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDPB_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PDG_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PDMS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PDMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDRS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDBS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDCT_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDLG_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDLG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDST_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDMN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDON_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDMNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDEA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PDSO_L, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PDDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ERR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JSBPD)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(PDnext)
                        .addComponent(jButton4)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PDS_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDS_IDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PDS_IDActionPerformed

    private void PDLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDLNActionPerformed

    private void PDPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDPBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //code to exit GUI
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JSBPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSBPDActionPerformed
        // TODO add your handling code here:
       //START  -->  codes to ensure no empty field before database insert
        if (PDS_ID.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please enter staff ID");
        }
            else if (PDLN.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Please enter Lastname of employee");
            }
            else if (PDFN.getText().equals("")){
                  JOptionPane.showMessageDialog(rootPane, "Please enter the Firstname of employee");
            }
               else {
        ////END  -->  codes to ensure no empty field before database insert
                
                
               //START --> new code to check if staff ID is existing
             
              try {
                //loading the driver
                 Class.forName("com.mysql.jdbc.Driver"); 
                 System.out.print("connection worked");
                 
                 //creating connection
                Connection newie2 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                 PreparedStatement flexie = newie2.prepareStatement("select * from persl_ds where S_ID = ? ");
            
                 //getting text (STaff ID) form Jtextfield
            flexie.setString(1,  PDS_ID.getText());
             ResultSet rs = flexie.executeQuery();
           JOptionPane.showMessageDialog(null , "checking Staff ID");
            
       if (rs.next()){
               JOptionPane.showMessageDialog(null, "Staff ID Exists");
               //wipng textfield if staff id is existing
               PDS_ID.setText(null);
                       }
        //end --> new code to check if staff ID is existing
       
       
     // if staff ID is new , then NEXT STEP        
               else{
         
                             
           //CODE TO INSERT VALUES NTO DATABASE
                
                //  SQL querry
         PreparedStatement stmtt1 = newie2.prepareStatement("insert into persl_ds(S_ID,L_N,F_N,M_N,PD_D_O_B,POB ,M_S,G_D,RA,NBS,C_T,LGA,ST,CMN,CMON,EM,SOO,LG )  "
                 + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" );
               //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmtt1.setString(1, PDS_ID.getText());
                stmtt1.setString(2, PDLN.getText());
                stmtt1.setString(3, PDFN.getText());
                stmtt1.setString(4, PDMN.getText());
                stmtt1.setString(5, ((JTextField)PDDOB.getDateEditor().getUiComponent()).getText());
                stmtt1.setString(6, PDPB.getText());
                stmtt1.setString(7, (String) PDMS.getSelectedItem());
                stmtt1.setString(8, (String) PDG.getSelectedItem());
                stmtt1.setString(9, PDRS.getText());
                stmtt1.setString(10, PDBS.getText());
                stmtt1.setString(11, PDCT.getText());
                stmtt1.setString(12, PDLG.getText());
                stmtt1.setString(13, (String) PDST.getSelectedItem());
                stmtt1.setString(14, PDMNO.getText());
                stmtt1.setString(15, PDON.getText());
                stmtt1.setString(16, PDEA.getText());
                stmtt1.setString(17, (String) PDSO.getSelectedItem());
                stmtt1.setString(18, PDSL.getText());
                
                       
                  stmtt1.addBatch();
                stmtt1.executeBatch();
                JOptionPane.showMessageDialog(rootPane, "new employee data saved");
                Clear();
               
            }                   
                      
       }
                             
                         catch (ClassNotFoundException | SQLException | HeadlessException e) {
                             JOptionPane.showMessageDialog(rootPane, "Error with STaff ID coding!!!");
                                                                             
                         }
        }
                                     
    }//GEN-LAST:event_JSBPDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PDS_IDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDS_IDKeyReleased
        // TODO add your handling code here:
     //   na here
    }//GEN-LAST:event_PDS_IDKeyReleased

    private void PDMNOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDMNOKeyReleased
        // TODO add your handling code here:
      // CODE TO ENSURE THat the textfield does not take alphabet input
       /*  CODE NOT GOOD ENOUGH, IT CANNOT TAKE MORE THAN 10 DIGITS
        try {
        x = Integer.parseInt(PDMNO.getText());
    } catch (NumberFormatException nfe) {
        PDMNO.setText("");
            }*/
       //if (PDMNO.getText().length()>=15) {
        //    getToolkit().beep();
          //  evt.consume();
    }//GEN-LAST:event_PDMNOKeyReleased
   // }
    private void PDMNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDMNOActionPerformed
        // TODO add your handling code here//:
    }//GEN-LAST:event_PDMNOActionPerformed

    private void PDONKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDONKeyReleased
        // TODO add your handling code here:
        // CODE TO ENSURE THat the textfield does not take alphabet input
      /*    try {
        zz = Integer.parseInt(PDON.getText());
    } catch (NumberFormatException nfe) {
        PDON.setText("");
    }*/
       //  if (PDON.getText().length()>=15) {
         //   getToolkit().beep();
          //  evt.consume();
         //}
    }//GEN-LAST:event_PDONKeyReleased

    private void PDMNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDMNOKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE ) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            
            evt.consume();
        }
    }//GEN-LAST:event_PDMNOKeyTyped

    private void PDONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDONKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED 
           char cc =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(cc) || (cc == KeyEvent.VK_BACKSPACE ) || cc == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_PDONKeyTyped

    private void PDONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDONActionPerformed

    private void PDnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDnextActionPerformed
        // TO open next form Relationship Details
          this.dispose();
          InfoCat nm = new  InfoCat();
          nm.show();
    }//GEN-LAST:event_PDnextActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // TO return to homepage
        this.dispose();
        HOMAPAGE nm = new HOMAPAGE();
        nm.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ERR;
    private javax.swing.JButton JSBPD;
    private javax.swing.JTextField PDBS;
    private javax.swing.JLabel PDBS_L;
    private javax.swing.JTextField PDCT;
    private javax.swing.JLabel PDCT_L;
    private com.toedter.calendar.JDateChooser PDDOB;
    private javax.swing.JLabel PDDOB_L;
    private javax.swing.JTextField PDEA;
    private javax.swing.JLabel PDEA_L;
    private javax.swing.JTextField PDFN;
    private javax.swing.JLabel PDFN_L;
    private javax.swing.JComboBox PDG;
    private javax.swing.JLabel PDG_L;
    private javax.swing.JLabel PDL;
    private javax.swing.JTextField PDLG;
    private javax.swing.JLabel PDLG_L;
    private javax.swing.JTextField PDLN;
    private javax.swing.JLabel PDLN_L1;
    private javax.swing.JTextField PDMN;
    private javax.swing.JTextField PDMNO;
    private javax.swing.JLabel PDMN_L;
    private javax.swing.JLabel PDMN_L1;
    private javax.swing.JComboBox PDMS;
    private javax.swing.JLabel PDMS_L;
    private javax.swing.JTextField PDON;
    private javax.swing.JLabel PDON_L;
    private javax.swing.JTextField PDPB;
    private javax.swing.JLabel PDPB_L;
    private javax.swing.JTextField PDRS;
    private javax.swing.JLabel PDRS_L;
    private javax.swing.JLabel PDSID_L;
    private javax.swing.JTextField PDSL;
    private javax.swing.JComboBox PDSO;
    private javax.swing.JLabel PDSO_L;
    private javax.swing.JComboBox PDST;
    private javax.swing.JLabel PDST_L;
    private javax.swing.JTextField PDS_ID;
    private javax.swing.JButton PDnext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
