
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *
    
/**
 *
 * @author TWS
 */
public class RelationshipDetails extends javax.swing.JFrame {
    
    
    public void Clear2(){
        
               JRDSI.setText(null);
               JRDLNS.setText(null);
               JRDMP.setText(null);
               JRDNCD.setText(null);
               JRDNC1.setText(null);
               JDRDDOB1.setDate(null);
               JRDSC1.setSelectedItem(null);
               JRDNC2.setText(null);
               JRDDOB2.setDate(null);
               JRDSC2.setSelectedItem(null);
               JRDNC3.setText(null);
               JRDDOB3.setDate(null);
               JRDSC3.setSelectedItem(null);
               JRDNC4.setText(null);
               JRDDOB4.setDate(null);
               JRDSC4.setSelectedItem(null);
               JRDNK.setText(null);
               JRDANK.setText(null);
               JRDNDOB.setDate(null);
               JRDNG.setSelectedItem(null);
               JRDNR.setText(null);
               JRDNMN.setText(null);
               JRDNON.setText(null);
               JRDNRAS.setText(null);
               JRDNNBS.setText(null);
               JRDNCT.setText(null);
               JRDLGA_L.setText(null);
               JRDST.setSelectedItem(null);
               JRDIC.setText(null);
               JRDIMN.setText(null);
    }
    /**
     * Creates new form RelationshipDetails
     */
    public RelationshipDetails() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        RDNCD_L = new javax.swing.JLabel();
        JRDNMN = new javax.swing.JTextField();
        RDNK_L = new javax.swing.JLabel();
        RDNRAS_L1 = new javax.swing.JLabel();
        RDNNBS_L = new javax.swing.JLabel();
        RDNC1_L = new javax.swing.JLabel();
        RDDOB3_L = new javax.swing.JLabel();
        JRDSC1 = new javax.swing.JComboBox();
        RDNON_L = new javax.swing.JLabel();
        JRDDOB2 = new com.toedter.calendar.JDateChooser();
        JRDNC1 = new javax.swing.JTextField();
        JRDST = new javax.swing.JComboBox();
        RDIC_L = new javax.swing.JLabel();
        JRDSC4 = new javax.swing.JComboBox();
        JRDIC = new javax.swing.JTextField();
        JRDNC2 = new javax.swing.JTextField();
        JRDDOB3 = new com.toedter.calendar.JDateChooser();
        JRDSI = new javax.swing.JTextField();
        RDST_L = new javax.swing.JLabel();
        RDNC3_L = new javax.swing.JLabel();
        JRDIMN = new javax.swing.JTextField();
        RDLGA_L = new javax.swing.JLabel();
        RDNMN_L = new javax.swing.JLabel();
        RDDOB1_L = new javax.swing.JLabel();
        JRDNON = new javax.swing.JTextField();
        RDNC4_L = new javax.swing.JLabel();
        RDNDOB_L = new javax.swing.JLabel();
        RDNRAS_L = new javax.swing.JLabel();
        RDLNS_L = new javax.swing.JLabel();
        RDNG_L = new javax.swing.JLabel();
        RDSC1_L = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JRDANK = new javax.swing.JTextArea();
        JRDNRAS = new javax.swing.JTextField();
        JRDNK = new javax.swing.JTextField();
        RDDOB2_L = new javax.swing.JLabel();
        JRDMP = new javax.swing.JTextField();
        JRDSC2 = new javax.swing.JComboBox();
        JRDNC3 = new javax.swing.JTextField();
        JRDNCD = new javax.swing.JTextField();
        JDRDDOB1 = new com.toedter.calendar.JDateChooser();
        RDNC2_L = new javax.swing.JLabel();
        JRDNCT = new javax.swing.JTextField();
        JRDLGA_L = new javax.swing.JTextField();
        JRDNG = new javax.swing.JComboBox();
        RDSC3_L = new javax.swing.JLabel();
        JRDNNBS = new javax.swing.JTextField();
        JRDNDOB = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RDNCT_L = new javax.swing.JLabel();
        JRDLNS = new javax.swing.JTextField();
        JRDDOB4 = new com.toedter.calendar.JDateChooser();
        RDNC4_L3 = new javax.swing.JLabel();
        JRDSC3 = new javax.swing.JComboBox();
        RDSC4_L = new javax.swing.JLabel();
        RDMP_L = new javax.swing.JLabel();
        RDSC2_L = new javax.swing.JLabel();
        RDNR_L = new javax.swing.JLabel();
        RDDOB4_L = new javax.swing.JLabel();
        RDIMN_L = new javax.swing.JLabel();
        RDSI = new javax.swing.JLabel();
        JRDNR = new javax.swing.JTextField();
        JRDNC4 = new javax.swing.JTextField();
        RELP_SAVE = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PILLOUT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relationship details");
        setBounds(new java.awt.Rectangle(800, 800, 800, 800));
        setPreferredSize(new java.awt.Dimension(800, 850));
        setResizable(false);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));

        RDNCD_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNCD_L.setText("Number of children");

        JRDNMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRDNMNActionPerformed(evt);
            }
        });
        JRDNMN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JRDNMNKeyTyped(evt);
            }
        });

        RDNK_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNK_L.setText("Name of next of kin");

        RDNRAS_L1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        RDNRAS_L1.setText("Current Residential Address");

        RDNNBS_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNNBS_L.setText("Nearest bus stop");

        RDNC1_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC1_L.setText("Name of Child 1");

        RDDOB3_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB3_L.setText("Date of birth child 3");

        JRDSC1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        RDNON_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNON_L.setText("Other numbers");

        JRDDOB2.setDateFormatString("yyyy-MM-dd ");

        JRDST.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abia ", "Adamawa ", "Akwa Ibom ", "FCT  Abuja", "Anambra ", "Bauchi ", "Bayelsa ", "Benue ", "Borno ", "Cross River ", "Delta ", "Ebonyi", "Edo ", "Ekiti ", "Enugu ", "Gombe", "Imo ", "Jigawa ", "Kaduna", "Kano ", "Katsina ", "Kebbi ", "Kogi ", "Kwara ", "Lagos ", "Nasarawa ", "Ogun ", "Ondo ", "Osun ", "Oyo", "Plateau ", "Rivers ", "Sokoto ", "Taraba", "Yobe", "Zamfara" }));

        RDIC_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDIC_L.setText("Person to Call in Emergency");

        JRDSC4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        JRDDOB3.setDateFormatString("yyyy-MM-dd ");

        JRDSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRDSIActionPerformed(evt);
            }
        });

        RDST_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDST_L.setText("State");

        RDNC3_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC3_L.setText("Name of child 3");

        JRDIMN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JRDIMNKeyTyped(evt);
            }
        });

        RDLGA_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDLGA_L.setText("Local Govt. Area");

        RDNMN_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNMN_L.setText("Mobile number");

        RDDOB1_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB1_L.setText("Date of birth Child 1");

        JRDNON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRDNONActionPerformed(evt);
            }
        });
        JRDNON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JRDNONKeyTyped(evt);
            }
        });

        RDNC4_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC4_L.setText("Name of child 4");

        RDNDOB_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNDOB_L.setText("Date of birth");

        RDNRAS_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNRAS_L.setText("Street number/ Street name");

        RDLNS_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDLNS_L.setText("Name of spouse");

        RDNG_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNG_L.setText("Gender");

        RDSC1_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC1_L.setText("Sex of child 1");

        JRDANK.setColumns(20);
        JRDANK.setRows(5);
        jScrollPane1.setViewportView(JRDANK);

        RDDOB2_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB2_L.setText("Date of birth Child 2");

        JRDMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JRDMPKeyTyped(evt);
            }
        });

        JRDSC2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        JDRDDOB1.setDateFormatString("yyyy-MM-dd ");

        RDNC2_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC2_L.setText("Name of Child 2");

        JRDNG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        RDSC3_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC3_L.setText("Sex of chld 3");

        JRDNDOB.setDateFormatString("yyyy-MM-dd ");

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setText("RELATIONSHIP DETAILS");

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel2.setText("NEXT OF KIN INFORMATION");

        RDNCT_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNCT_L.setText("City / Town");

        JRDDOB4.setDateFormatString("yyyy-MM-dd ");

        RDNC4_L3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNC4_L3.setText("Address of next of kin");

        JRDSC3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        RDSC4_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC4_L.setText("Sex of child 4");

        RDMP_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDMP_L.setText("Mobile number");

        RDSC2_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSC2_L.setText("Sex of child 2");

        RDNR_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDNR_L.setText("Relationship");

        RDDOB4_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDDOB4_L.setText("Date of birth child 4");

        RDIMN_L.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDIMN_L.setText("Mobile no");

        RDSI.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RDSI.setText("Staff ID");

        JRDNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRDNRActionPerformed(evt);
            }
        });

        JRDNC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRDNC4ActionPerformed(evt);
            }
        });

        RELP_SAVE.setText("Save");
        RELP_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RELP_SAVEActionPerformed(evt);
            }
        });

        jButton2.setText("back");
        jButton2.setToolTipText("return to previous menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PILLOUT.setText("eXIT");
        PILLOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILLOUTActionPerformed(evt);
            }
        });

        jButton4.setText("home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RDNK_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRDNK, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RDNCD_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRDNCD, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RDMP_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRDMP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RDSI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDLNS_L, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JRDLNS, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(JRDSI)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDNC1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNC2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNC4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDNC1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDNC2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDNC3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDNC4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JRDDOB4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(RDDOB2_L, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(RDDOB3_L, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(RDDOB4_L, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(RDDOB1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JDRDDOB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JRDDOB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JRDDOB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RDSC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RDSC2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RDSC4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(JRDSC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JRDSC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JRDSC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JRDSC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(RDSC1_L, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(RDNRAS_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RDNDOB_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDNC4_L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDNR_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RDNMN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JRDNR, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JRDNDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(JRDNMN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RDLGA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JRDLGA_L, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RDNON_L, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RDNG_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JRDNON, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JRDNG, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(RDNCT_L, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JRDNCT, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(RDNNBS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JRDNNBS))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(RDNRAS_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JRDNRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(RDIMN_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JRDIMN))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RDST_L, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RDIC_L))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JRDIC, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JRDST, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(RELP_SAVE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(PILLOUT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(RDSC1_L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JRDSC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RDSI)
                                    .addComponent(JRDSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RDLNS_L)
                                            .addComponent(JRDLNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RDMP_L)
                                            .addComponent(JRDMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RDNCD_L)
                                            .addComponent(JRDNCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RDNC1_L)
                                        .addGap(8, 8, 8)
                                        .addComponent(JRDNC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(RDDOB1_L)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JDRDDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RDDOB2_L)
                                    .addComponent(RDSC2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RDNC2_L))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JRDNC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JRDDOB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JRDSC2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RDNC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RDDOB3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(RDSC3_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JRDNC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDDOB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDSC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDSC4_L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RDNC4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RDDOB4_L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRDNC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDSC4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JRDDOB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RDNK_L)
                    .addComponent(JRDNK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RDNC4_L3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RDNDOB_L)
                                .addComponent(RDNG_L)
                                .addComponent(JRDNG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JRDNDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDNR_L)
                            .addComponent(JRDNR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDNMN_L)
                            .addComponent(RDNON_L)
                            .addComponent(JRDNMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JRDNON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RDNRAS_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDNRAS_L)
                            .addComponent(JRDNRAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDNCT_L)
                            .addComponent(JRDNCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDNNBS_L)
                            .addComponent(JRDNNBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDLGA_L)
                            .addComponent(JRDLGA_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RDST_L)
                            .addComponent(JRDST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDIC_L)
                            .addComponent(JRDIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RDIMN_L)
                            .addComponent(JRDIMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RELP_SAVE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(PILLOUT)
                    .addComponent(jButton1))
                .addGap(101, 101, 101))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JRDNC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRDNC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRDNC4ActionPerformed

    private void JRDNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRDNRActionPerformed
        // TODO add your handling code here:
        JRDNR.setSelectedTextColor(Color.BLUE);
    }//GEN-LAST:event_JRDNRActionPerformed

    private void JRDSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRDSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRDSIActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TO open family details page
        this.dispose();
        InfoCat nm = new InfoCat();
        nm.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JRDNMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRDNMNActionPerformed
        // TODO add your handling code here:
        JRDNMN.setSelectionColor(Color.red);
    }//GEN-LAST:event_JRDNMNActionPerformed

    private void JRDNMNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRDNMNKeyTyped
      // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c1 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c1) || (c1 == KeyEvent.VK_BACKSPACE ) || c1 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_JRDNMNKeyTyped

    private void JRDNONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRDNONKeyTyped
    // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c11 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c11) || (c11 == KeyEvent.VK_BACKSPACE ) || c11 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_JRDNONKeyTyped

    private void JRDIMNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRDIMNKeyTyped
      // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c12 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c12) || (c12 == KeyEvent.VK_BACKSPACE ) || c12 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_JRDIMNKeyTyped

    private void PILLOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILLOUTActionPerformed
        // CLOSE WINDOWS
        System.exit(0);
    }//GEN-LAST:event_PILLOUTActionPerformed

    private void JRDMPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JRDMPKeyTyped
        // SETTING TEXTFIELD TO TAKE ONLY NUMERICAL VALES
        //ALSO TO MAKE IT BEEP WHEN ALPHABETS ARE CLICKED
        char c13 =  evt.getKeyChar();
        //code to allow backspace and delete condition
        if (! (Character.isDigit(c13) || (c13 == KeyEvent.VK_BACKSPACE ) || c13 == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_JRDMPKeyTyped

    private void RELP_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RELP_SAVEActionPerformed
        // checking if Staff ID textfield is empty and returning a mesage if it is empty
        if (JRDSI.getText().equals("")){
                  JOptionPane.showMessageDialog(rootPane, "Please enter the Staff ID of employee");
            }
               else {
                          
         try{ 
             
              //loading the driver
                 Class.forName("com.mysql.jdbc.Driver"); 
                 System.out.print("connection worked");
                 
                 //creating connection
                Connection newie3 = DriverManager.getConnection("jdbc:mysql://localhost/employee_db", "root", "jesus");
                System.out.print("database connected");
                 PreparedStatement flexie2 = newie3.prepareStatement("select * from persl_ds where S_ID = ? ");
            
                 //getting text (STaff ID) form Jtextfield
            flexie2.setString(1,  JRDSI.getText());
             ResultSet rs = flexie2.executeQuery();
           JOptionPane.showMessageDialog(null , "checking Staff ID");
            
       if (rs.next()){
           //confirming from datbase if user-given Staff Id exist
               JOptionPane.showMessageDialog(null, "Staff ID Exists ");
               
                       }
        //end --> new code to check if staff ID is existing
       
       
     // if staff ID is new , then NEXT STEP        
               else {
           JOptionPane.showMessageDialog(rootPane, "Please enter an existing Staff ID");
                // JRDSI.setText(null);
          Clear2();
               }
               PreparedStatement stmttz = newie3.prepareStatement("insert into relp_ds(S_ID, RDLNS,RDMP, RDNCD,RDNC1,DRDDOB1,RDSC1,RDNC2,RDDOB2,RDSC2,RDNC3,RDDOB3,RDSC3,RDNC4,RDDOB4,RDSC4,RDNK,RDANK,RDNDOB,RDNG,RDNR,RDNMN,RDNON,RDNRAS,RDNNBS,RDNCT,RDLGA,RDST,RDIC,RDIMN )  "
                 + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" );
               //for string value stmtt1.setInt(1, Integer.valueOf(PDS_ID.getText()));
                stmttz.setString(1, JRDSI.getText());
                stmttz.setString(2, JRDLNS.getText());
                stmttz.setString(3, JRDMP.getText());
                stmttz.setString(4, JRDNCD.getText());
                stmttz.setString(5, JRDNC1.getText());
                stmttz.setString(6, ((JTextField)JDRDDOB1.getDateEditor().getUiComponent()).getText());
                stmttz.setString(7, (String) JRDSC1.getSelectedItem());
                stmttz.setString(8, JRDNC2.getText());
                stmttz.setString(9, ((JTextField)JRDDOB2.getDateEditor().getUiComponent()).getText());
                stmttz.setString(10, (String) JRDSC2.getSelectedItem());
                stmttz.setString(11, JRDNC3.getText());
                stmttz.setString(12, ((JTextField)JRDDOB3.getDateEditor().getUiComponent()).getText());
                stmttz.setString(13, (String) JRDSC3.getSelectedItem());
                stmttz.setString(14, JRDNC4.getText());
                stmttz.setString(15, ((JTextField)JRDDOB4.getDateEditor().getUiComponent()).getText());
                stmttz.setString(16, (String) JRDSC4.getSelectedItem());
                stmttz.setString(17, JRDNK.getText());
                stmttz.setString(18, JRDANK.getText());
                stmttz.setString(19, ((JTextField)JRDNDOB.getDateEditor().getUiComponent()).getText());
                stmttz.setString(20, (String) JRDNG.getSelectedItem());
                stmttz.setString(21, JRDNR.getText());
                stmttz.setString(22, JRDNMN.getText());
                stmttz.setString(23, JRDNON.getText());
                stmttz.setString(24, JRDNRAS.getText());
                stmttz.setString(25, JRDNNBS.getText());
                stmttz.setString(26, JRDNCT.getText());
                stmttz.setString(27, JRDLGA_L.getText());
                stmttz.setString(28, (String) JRDST.getSelectedItem());
                stmttz.setString(29, JRDIC.getText());
                stmttz.setString(30, JRDIMN.getText());
                   
                stmttz.addBatch();
                stmttz.executeBatch();
                JOptionPane.showMessageDialog(rootPane, "new employee relationship details saved");
                Clear2();
                
                              }                                
                         catch (ClassNotFoundException | SQLException | HeadlessException e) {
                             JOptionPane.showMessageDialog(rootPane, "please ENTER an existing Staff ID \n  SSand fill all the fields again");
                        }                                                
                         }
        
    }//GEN-LAST:event_RELP_SAVEActionPerformed

    private void JRDNONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRDNONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRDNONActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TO display home screen
         this.dispose();
        HOMAPAGE nm = new HOMAPAGE();
        nm.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TO clear data in field controls
        Clear2();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelationshipDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelationshipDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelationshipDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelationshipDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelationshipDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDRDDOB1;
    private javax.swing.JTextArea JRDANK;
    private com.toedter.calendar.JDateChooser JRDDOB2;
    private com.toedter.calendar.JDateChooser JRDDOB3;
    private com.toedter.calendar.JDateChooser JRDDOB4;
    private javax.swing.JTextField JRDIC;
    private javax.swing.JTextField JRDIMN;
    private javax.swing.JTextField JRDLGA_L;
    private javax.swing.JTextField JRDLNS;
    private javax.swing.JTextField JRDMP;
    private javax.swing.JTextField JRDNC1;
    private javax.swing.JTextField JRDNC2;
    private javax.swing.JTextField JRDNC3;
    private javax.swing.JTextField JRDNC4;
    private javax.swing.JTextField JRDNCD;
    private javax.swing.JTextField JRDNCT;
    private com.toedter.calendar.JDateChooser JRDNDOB;
    private javax.swing.JComboBox JRDNG;
    private javax.swing.JTextField JRDNK;
    private javax.swing.JTextField JRDNMN;
    private javax.swing.JTextField JRDNNBS;
    private javax.swing.JTextField JRDNON;
    private javax.swing.JTextField JRDNR;
    private javax.swing.JTextField JRDNRAS;
    private javax.swing.JComboBox JRDSC1;
    private javax.swing.JComboBox JRDSC2;
    private javax.swing.JComboBox JRDSC3;
    private javax.swing.JComboBox JRDSC4;
    private javax.swing.JTextField JRDSI;
    private javax.swing.JComboBox JRDST;
    private javax.swing.JButton PILLOUT;
    private javax.swing.JLabel RDDOB1_L;
    private javax.swing.JLabel RDDOB2_L;
    private javax.swing.JLabel RDDOB3_L;
    private javax.swing.JLabel RDDOB4_L;
    private javax.swing.JLabel RDIC_L;
    private javax.swing.JLabel RDIMN_L;
    private javax.swing.JLabel RDLGA_L;
    private javax.swing.JLabel RDLNS_L;
    private javax.swing.JLabel RDMP_L;
    private javax.swing.JLabel RDNC1_L;
    private javax.swing.JLabel RDNC2_L;
    private javax.swing.JLabel RDNC3_L;
    private javax.swing.JLabel RDNC4_L;
    private javax.swing.JLabel RDNC4_L3;
    private javax.swing.JLabel RDNCD_L;
    private javax.swing.JLabel RDNCT_L;
    private javax.swing.JLabel RDNDOB_L;
    private javax.swing.JLabel RDNG_L;
    private javax.swing.JLabel RDNK_L;
    private javax.swing.JLabel RDNMN_L;
    private javax.swing.JLabel RDNNBS_L;
    private javax.swing.JLabel RDNON_L;
    private javax.swing.JLabel RDNRAS_L;
    private javax.swing.JLabel RDNRAS_L1;
    private javax.swing.JLabel RDNR_L;
    private javax.swing.JLabel RDSC1_L;
    private javax.swing.JLabel RDSC2_L;
    private javax.swing.JLabel RDSC3_L;
    private javax.swing.JLabel RDSC4_L;
    private javax.swing.JLabel RDSI;
    private javax.swing.JLabel RDST_L;
    private javax.swing.JButton RELP_SAVE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
